var _TD={loading:[],init:function(){var a,c={init:function(){document.getElementById("post").style.display="none";document.getElementById("pre").style.display="block";document.getElementById("over").style.display="none";c.lang.setMoney(c.cfg.money);c.lang.setWave(c.wave);c.lang.setScore(c.score);var a=new c.spriteSheetHandler;a.init({type:"monster"});a.init({type:"explode"});a.init({type:"scene"});a.init({type:"turret"});c.map=new c.createMap},start:function(){this.runner.addEventListener("click",
c.onClick_runner,!1);this.pauseElement.addEventListener("click",c.onClick_pause,!1);c.bldCtrl=new c.buildingController;for(var a=0;a<this.terminalNodePool.length;a++){var d=this.terminalNodePool[a];this.aliveTerminals[d]=new c.terminalBuilding(d.position,d,c.cfg.Buildings["building-5"]);c.bloodBarQueue.push(new c.bloodBar(this.aliveTerminals[d]))}this.ucx.clearRect(0,0,this.width,this.height);c.lang.showBuildingInfo()},onClick_runner:function(){c.beforeRun?(c.beforeRun=!1,document.getElementById("run").style.display=
"none",document.getElementById("pause").style.display="block",c.step()):(c.pause=!1,document.getElementById("run").style.display="none",document.getElementById("pause").style.display="block")},onClick_pause:function(){c.pause=!0;document.getElementById("run").style.display="block";document.getElementById("pause").style.display="none"},step:function(){_this=c;if(c.GameOver)clearTimeout(_this._st),c.gameOver();else{if(0==c.waitingForNextWave&&0==_this.monsterQueue.length)c.waitingForNextWave=!0,c.lang.levelUp(),
c.lang.setWave(c.wave+1),setTimeout(c.buildNextWave,3E3);else{if(!c.pause){for(_this.ucx.clearRect(0,0,_this.cfg.width,_this.cfg.height);0<_this.eventQueue.length;){var a=_this.eventQueue.shift();_this.drawer(a)}for(a=_this.grassQueue.length;0<a;){a--;var d=_this.grassQueue.shift();d.alive&&(_this.eventQueue.push(d),_this.grassQueue.push(d))}for(a=_this.irremovalbeGrassQueue.length;0<a;)a--,d=_this.irremovalbeGrassQueue.shift(),d.alive&&(_this.eventQueue.push(d),_this.irremovalbeGrassQueue.push(d))}for(var a=
_this.monsterQueue.length,e;0<a;)a--,d=_this.monsterQueue.shift(),1==d.move()&&_this.monsterQueue.push(d);for(a=_this.buildingQueue.length;0<a;)a--,d=_this.buildingQueue.shift(),1==d.move()&&_this.buildingQueue.push(d);for(a=_this.inBuildingQueue.length;0<a;)a--,d=_this.inBuildingQueue.shift(),1==d.move()&&_this.inBuildingQueue.push(d);if(!c.pause)for(e in c.deadTerminals)c.deadTerminals.hasOwnProperty(e)&&(d=c.deadTerminals[e],d.move());for(e in c.aliveTerminals)c.aliveTerminals.hasOwnProperty(e)&&
(d=c.aliveTerminals[e],0==d.move()&&(c.deadTerminals[e]=d,delete c.aliveTerminals[e]));if(0<c.terminalTmpBuffer.length)for(c.terminalTmpBuffer.sort(function(a,c){return a.position[1]-c.position[1]});0<c.terminalTmpBuffer.length;)c.eventQueue.push(c.terminalTmpBuffer.shift());if(!c.pause){for(a=_this.bloodBarQueue.length;0<a;)a--,d=_this.bloodBarQueue.shift(),1==d.move()&&_this.bloodBarQueue.push(d);for(a=_this.bulletQueue.length;0<a;)a--,d=_this.bulletQueue.shift(),1==d.move()&&_this.bulletQueue.push(d)}}_this._st=
setTimeout(function(){_this.step()},30)}}};for(a=0;this.loading[a];a++)this.loading[a](c);c.init()}};
_TD.loading.push(function(a){a.cfg={height:500,width:500,Restriction:[[[100,0],[0,100]],[[400,500],[500,400]]],taRestriction:[[450,500],[500,450]],dirC:[[1,0,6],[-1,0,2],[0,1,4],[0,-1,8]],dirD:[[-1,-1,1],[-1,1,3],[1,-1,7],[1,1,5]],Dir:[[[1,0,6],[-1,0,2],[0,1,4],[0,-1,8]],[[-1,-1,1],[-1,1,3],[1,-1,7],[1,1,5]]],buildingR:20,monsterR:10,bulletSize1:1,bulletSize2:1,bulletSize3:2,maxLevel:3,maxNumberOfMonsterPerWave:10,money:500,density:10,speedMapping:function(a){return 350>=a?1:700>=a?.9:.5},monster:function(a,
b){a.fillStyle="green";a.beginPath();a.arc(b[0],b[1],5,0,2*Math.PI);a.fill()},mouse:function(a,b,d){this.clearAll(a,b);a.beginPath();a.arc(d.position[0],d.position[1],this.buildingR,0,2*Math.PI,!1);a.fillStyle="rgba(225,0,0,0.2)";1==d.buildable&&(a.fillStyle="rgba(0,255,0,0.2)");a.fill();a.lineWidth=1;a.strokeStyle="#003300";a.stroke()},clearAll:function(a,b){a.clearRect(0,0,b.width,b.height)},bar:function(a,b){var d=b.position,e=b.positionIn;a.beginPath();a.strokeStyle="black";a.lineWidth=5;a.moveTo(d[0][0],
d[0][1]);a.lineTo(d[1][0],d[1][1]);a.stroke();a.beginPath();a.strokeStyle=1==b.shield?"rgba(68, 51, 250, 1)":"lightgreen";a.lineWidth=3;a.moveTo(e[0][0],e[0][1]);a.lineTo(e[1][0],e[1][1]);a.stroke()},bullet_small:function(c,b){void 0==b.exploding?(c.beginPath(),c.arc(b.position[0],b.position[1],this.bulletSize1,0,2*Math.PI,!1),c.fillStyle="rgba(118, 93, 5, 1)",c.fill()):a.drawSprite(c,"explode",b.exploding,b.position[0],b.position[1])},bullet_middle:function(c,b){void 0==b.exploding?(c.beginPath(),
c.arc(b.position[0],b.position[1],this.bulletSize2,0,2*Math.PI,!1),c.fillStyle="#40CF8E",c.fill()):a.drawSprite(c,"explode",b.exploding,b.position[0],b.position[1])},bullet_large:function(c,b){void 0==b.exploding?(c.beginPath(),c.arc(b.position[0],b.position[1],this.bulletSize3,0,2*Math.PI,!1),c.fillStyle="#AB4F80",c.fill()):a.drawSprite(c,"explode",b.exploding,b.position[0],b.position[1])},bullet_layser:function(a,b){void 0!=b.position&&(void 0==b.hostType||"building-4"==b.hostType?(a.beginPath(),
a.strokeStyle="rgba(210, 50, 205, 1)",a.lineWidth=2):"monster-4"==b.hostType?(a.beginPath(),a.strokeStyle="rgba(156, 81, 58, 1)",a.lineWidth=2):(a.beginPath(),a.strokeStyle="rgba(24, 85, 205, 1)",a.lineWidth=3),a.lineCap="round",a.moveTo(b.origin[0],b.origin[1]),a.lineTo(b.position[0],b.position[1]),a.stroke())},bullet_missile:function(c,b){c.beginPath();var d,e;if(void 0!=b.track&&void 0!=b.track[0]){c.moveTo(b.track[0][0][0],b.track[0][0][1]);for(d=0;d<b.track.length;d++)e=b.track[d],c.strokeStyle=
"rgba(251, 212, 40, 0.5)",c.lineWidth=1,c.lineTo(e[1][0],e[1][1]);c.stroke()}if(void 0!=b.exploding)a.drawSprite(c,"explode",b.exploding,b.position[0],b.position[1]);else if(1<b.track.length)if(b.catnon){d=e[1][0];var f=e[1][1],g=a.catnonImg;e=a.lang.getAngle360([e[0],[d-10,f]],e);c.save();c.translate(d,f);c.rotate(e);c.translate(-21,-13);c.drawImage(g,0,0,42,26);c.restore()}else c.beginPath(),c.strokeStyle="rgba(255, 255, 255, 1)",c.lineWidth=2,c.moveTo(e[0][0],e[0][1]),c.lineTo(e[1][0],e[1][1]),
c.stroke()},grass:function(c,b){var d,e,f=b.position[0],g=b.position[1],k=a.gSpriteSheets.scene;spt=k.getStats(b.spritename);d=b.spritename[7];"6"==d||"9"==d||"0"==d?(d=spt.cx,e=spt.cy,c.drawImage(k.img,spt.x,spt.y,spt.w,spt.h,f+d,g+e,spt.w,spt.h)):(d=spt.cx/2,e=spt.cy/2,c.drawImage(k.img,spt.x,spt.y,spt.w,spt.h,f+d,g+e,spt.w/2,spt.h/2))},mst1:function(c,b){a.drawSprite(c,b.type,b.spritename,b.position[0],b.position[1])},mst2:function(c,b){a.drawSprite(c,b.type,b.spritename,b.position[0],b.position[1])},
mst3:function(c,b){a.drawSprite(c,b.type,b.spritename,b.position[0],b.position[1])},mst4:function(c,b){a.drawSprite(c,b.type,b.spritename,b.position[0],b.position[1])},bld1:function(c,b){var d=b.position[0],e=b.position[1],f=a.gSpriteSheets.turret;a.turretFrame[b.type];spt=f.getStats(a.turretFrame[b.type][b.frame]);c.save();c.translate(d,e);c.rotate(b.angle);c.translate(-25,-15);c.drawImage(f.img,spt.x,spt.y,spt.w,spt.h,0,0,40,30);c.restore();void 0!=b.showRange&&(d=b.showRange,c.beginPath(),c.arc(b.position[0],
b.position[1],d,0,2*Math.PI,!1),c.lineWidth=.5,c.strokeStyle="white",c.stroke())},bld2:function(c,b){var d=b.position[0],e=b.position[1],f=a.gSpriteSheets.turret;a.turretFrame[b.type];spt=f.getStats(a.turretFrame[b.type][b.frame]);c.save();c.translate(d,e);c.rotate(b.angle);c.translate(-25,-15);c.drawImage(f.img,spt.x,spt.y,spt.w,spt.h,0,0,40,30);c.restore();void 0!=b.showRange&&(d=b.showRange,c.beginPath(),c.arc(b.position[0],b.position[1],d,0,2*Math.PI,!1),c.lineWidth=.5,c.strokeStyle="white",c.stroke())},
bld3:function(c,b){var d=b.position[0],e=b.position[1],f=a.gSpriteSheets.turret;a.turretFrame[b.type];spt=f.getStats(a.turretFrame[b.type][b.frame]);c.save();c.translate(d,e);c.rotate(b.angle);c.translate(-25,-15);c.drawImage(f.img,spt.x,spt.y,spt.w,spt.h,0,0,40,30);c.restore();void 0!=b.showRange&&(d=b.showRange,c.beginPath(),c.arc(b.position[0],b.position[1],d,0,2*Math.PI,!1),c.lineWidth=.5,c.strokeStyle="white",c.stroke())},bld4:function(c,b){var d=b.position[0],e=b.position[1],f=a.gSpriteSheets.turret;
a.turretFrame[b.type];spt=f.getStats(a.turretFrame[b.type][b.frame]);c.save();c.translate(d,e);c.rotate(b.angle);c.translate(-22,-19);c.drawImage(f.img,spt.x,spt.y,spt.w,spt.h,0,0,41,38);c.restore();void 0!=b.showRange&&(d=b.showRange,c.beginPath(),c.arc(b.position[0],b.position[1],d,0,2*Math.PI,!1),c.lineWidth=.5,c.strokeStyle="white",c.stroke())},bld5:function(c,b){var d=b.position[0],e=b.position[1],f=a.gSpriteSheets.scene,g="TA"==b.tid?f.getStats("tower_02.png"):f.getStats("tower_01.png");c.drawImage(f.img,
g.x,g.y,g.w,g.h,d+(g.cx+10),e+(g.cy+5),15,50);void 0!=b.showRange&&(f=b.showRange,c.beginPath(),c.arc(d,e,f,0,2*Math.PI,!1),c.lineWidth=.5,c.strokeStyle="white",c.stroke())},bld5_2:function(c,b){var d=b.position[0],e=b.position[1],f=a.gSpriteSheets.scene,g=f.getStats("tower_03.png");c.drawImage(f.img,g.x,g.y,g.w,g.h,d+(g.cx+7),e+(g.cy-20),15,15);void 0!=b.showRange&&(f=b.showRange,c.beginPath(),c.arc(d,e,f,0,2*Math.PI,!1),c.lineWidth=.5,c.strokeStyle="white",c.stroke())},bld6:function(c,b){var d=
b.position[0],e=b.position[1],f=a.gSpriteSheets.turret;spt=f.getStats("turret_06.png");c.save();c.translate(d,e);c.rotate(b.angle);c.translate(-20,-20);c.drawImage(f.img,spt.x,spt.y,spt.w,spt.h,0,0,40,40);c.restore();void 0!=b.showRange&&(d=b.showRange,c.beginPath(),c.arc(b.position[0],b.position[1],d,0,2*Math.PI,!1),c.lineWidth=.5,c.strokeStyle="white",c.stroke())},game_over:function(c,b){c.font="30px Georgia";c.fillText("Game Over!",150,200);c.font="50px Verdana";var d=c.createLinearGradient(0,
0,a.uc.width,0);d.addColorStop("0","magenta");d.addColorStop("0.5","blue");d.addColorStop("1.0","red");c.fillStyle=d;c.fillText("Big smile!",120,300);c.font="20px Arial";c.fillStyle="rgba(194, 251, 50, 1)";c.fillText("Wave: "+b.wave,160,350);null!=b.score&&(c.font="20px Arial",c.fillStyle="rgba(194, 251, 50, 1)",c.fillText("Score: "+b.score,160,400))},Arsenal:{bullet_small:{speed:1E3,damageRange:7,exploding:[2,3,4,5,4]},bullet_middle:{speed:8,damageRange:20,exploding:[3,4,5,6,5]},bullet_large:{speed:7,
damageRange:30,exploding:[4,6,8,10,8]},bullet_layser:{speed:1E3,damageRange:1,exploding:null},bullet_missile:{speed:3,damageRange:55,exploding:[3,4,5,6,7,7,5]}},monster_1_base_live:125,monster_2_base_live:150,monster_3_base_live:175,monster_4_base_live:200,monster_1_base_price:10,monster_2_base_price:12,monster_3_base_price:15,monster_4_base_price:20,monster_frequency:500,Monsters:{"monster-1":{type:"monster-1",range:40,speed:1,damage:20,frequency:1200,cannonType:"bullet_small",live:function(){return a.cfg.monster_1_base_live},
price:function(){return a.cfg.monster_1_base_price}},"monster-2":{type:"monster-2",range:50,speed:.9,damage:25,frequency:1200,cannonType:"bullet_small",live:function(){return a.cfg.monster_2_base_live},price:function(){return a.cfg.monster_2_base_price}},"monster-3":{type:"monster-3",range:60,speed:.8,damage:30,frequency:1200,cannonType:"bullet_small",live:function(){return a.cfg.monster_3_base_live},price:function(){return a.cfg.monster_3_base_price}},"monster-4":{type:"monster-4",range:70,speed:.75,
damage:1,frequency:30,cannonType:"bullet_layser",live:function(){return a.cfg.monster_4_base_live},price:function(){return a.cfg.monster_4_base_price}}},Buildings:{"building-1":{type:"building-1",cannonType:"bullet_small",frequency:300,live:80,price:200,range:55,damage:30,cannonLen:10},"building-2":{type:"building-2",cannonType:"bullet_middle",frequency:600,live:100,price:250,range:70,damage:55,cannonLen:12},"building-3":{type:"building-3",cannonType:"bullet_large",frequency:800,live:100,price:300,
range:80,damage:90,cannonLen:15},"building-4":{type:"building-4",cannonType:"bullet_layser",frequency:30,live:100,price:500,range:60,damage:5,cannonLen:20},"building-5":{type:"building-5",cannonType:"bullet_layser",frequency:30,live:1E3,price:500,range:100,damage:2,cannonLen:0},"building-6":{type:"building-6",cannonType:"bullet_missile",frequency:3E3,live:100,price:1E3,range:125,damage:400,missileNumber:1,cannonLen:5}},upgradeMapping:{"building-1":[{damage:2,frequency:.9,range:1.1,live:2,price:1700},
{damage:2.5,frequency:.8,range:1.2,live:3,price:5500},{damage:2.5,frequency:.8,range:1.5,live:4,price:7250}],"building-2":[{damage:1.5,frequency:.9,range:1.2,live:2,price:1E3},{damage:2,frequency:.8,range:1.2,live:3,price:3800},{damage:3.2,frequency:.7,range:1.7,live:6,price:9E3}],"building-3":[{damage:1.5,frequency:.9,range:1.2,live:2,price:1200},{damage:1.7,frequency:.8,range:1.3,live:3,price:5E3},{damage:2.5,frequency:.7,range:1.5,live:5,price:8200}],"building-4":[{damage:2,frequency:1,range:1.2,
live:2,price:1500},{damage:3,frequency:1,range:1.3,live:3,price:4500},{damage:3,frequency:1,range:1.5,live:4,price:8700}],"building-5":[{damage:1,frequency:1,range:1,live:2,price:5E3}],"building-6":[{damage:1.2,frequency:.95,missile:1,range:1.2,live:2,price:2E3},{damage:1.2,frequency:.9,missile:2,range:1.3,live:3,price:3900},{damage:1.5,frequency:.9,missile:3,range:1.5,live:4,price:7E3}]}}});
_TD.loading.push(function(a){a.version="0.1.0";a.money=500;a.score=0;a.wave=0;a.maxNumberOfMonsterPerWave=a.cfg.maxNumberOfMonsterPerWave;a.GameOver=!1;a.waitingForNextWave=!1;a.pause=!1;a.root=null;null==a.map;a.validMap=!1;a.bldCtrl=null;a.runner=null;a.beforeRun=!0;a.reStart=null;a.eventQueue=[];a.monsterQueue=[];a.buildingQueue=[];a.inBuildingQueue=[];a.bulletQueue=[];a.bloodBarQueue=[];a.grassQueue=[];a.irremovalbeGrassQueue=[];a.terminalNodePool=[];a.aliveTerminals={};a.deadTerminals={};a.terminalTmpBuffer=
[];a.rawMapData=null;a.path=null;a.gSpriteSheets={};a.monsterFrame={};a.monsterTypes=["monster-1","monster-2","monster-3","monster-4"];a.monsterSpriteSource="img/zombie.png";a.bulletTypes=["bullet_small","bullet_middle","bullet_large","bullet_missile"];a.explodeFrame={};a.explodeSpriteSource="img/explode.png";a.sceneFrame={};a.sceneSpriteSource="img/scene.png";a.turretFrame={};a.turretSpriteSource="img/turret.png";a.uc=document.getElementById("td-canvas-1");a.ucx=a.uc.getContext("2d");a.uc2=document.getElementById("td-canvas-2");
a.ucx2=a.uc2.getContext("2d");a.uc0=document.getElementById("td-canvas-background");a.ucx0=a.uc0.getContext("2d");a.mapData=null;a.waitingToBuild=null;a.waitingToChange=null;a.moneyElement=document.getElementById("money");a.waveElement=document.getElementById("wave");a.scoreElement=document.getElementById("score");a.panelElement=document.getElementById("info");a.runner=document.getElementById("run");a.pauseElement=document.getElementById("pause");a.canvasBody=document.getElementById("td-canvas");
a.redoBody=document.getElementById("redo");a.undoBody=document.getElementById("undo");a.submitBody=document.getElementById("submit");a.catnonImg=document.getElementById("catnon")});
_TD.loading.push(function(a){a.lang={isOnLeft:function(a,b){var d=a[0],e=a[1];return d==b||e==b?!1:0>Number(((d[0]-b[0])*(e[1]-b[1])-(d[1]-b[1])*(e[0]-b[0])-0).toFixed(5))?!0:!1},isInCircle:function(a,b){var d=Math.sqrt((b[0]-a[0])*(b[0]-a[0])+(b[1]-a[1])*(b[1]-a[1])),d=Number(d.toFixed(5)),e=Number(a[2].toFixed(5));return d<e?1:d==e?0:-1},Create2DArray:function(a,b){for(var d=[],e=0;e<a;e++){for(var f=[],g=0;g<b;g++)f[g]=0;d[e]=f}return d},drawOneSet:function(a,b,d){a.lineWidth=1;a.lineCap="round";
a.strokeStyle=d;for(d=0;d<b.length;d++)a.beginPath(),a.moveTo(b[d][0][0],b[d][0][1]),a.lineTo(b[d][1][0],b[d][1][1]),a.stroke()},drawArray:function(a,b,d){a.lineWidth=1;a.lineCap="round";a.strokeStyle=d;a.beginPath();for(d=0;d<b.length;d++)0==d?a.moveTo(b[d][0][0],b[d][0][1]):(a.lineTo(b[d][0][0],b[d][0][1]),a.stroke())},refineMap:function(a){for(var b=a.length,d=a[0].length,e=0;e<b;e++)for(var f=0;f<d;f++)1==a[e][f]&&(0==a[e-1][f]&&0==a[e+1][f]?a[e][f]=0:0==a[e][f-1]&&0==a[e][f+1]&&(a[e][f]=0))},
drawOutline:function(c,b){var d=0,e=0,f,g,k,h,u=[];c.globalCompositeOperation="source-over";g=a.gSpriteSheets.scene;k=g.getStats("grass_15.png");var v=k.cx,y=k.cy,r=this.randomNum(5)+3;this.randomNum(30);for(f=0;f<b.length;f++)0==r?(r=this.randomNum(5)+3,f+=this.randomNum(20)+5):(r--,h=b[f],this.ok2Draw(h[0],h[1])&&(4==this.getCurDir([d,e],h)?(0==u.length?u.push([d,e]):this.pointEq(u[u.length-1],[d,e])||u.push([d,e]),u.push(h)):c.drawImage(g.img,k.x,k.y,k.w,k.h,h[0]+v,h[1]+y-3,k.w,k.h)),d=h[0],e=
h[1]);for(;0<u.length;)h=u.pop(),c.drawImage(g.img,k.x,k.y,k.w,k.h,h[0]+v,h[1]+y-3,k.w,k.h)},onClick_restart:function(){a.reStart.removeEventListener("click",a.lang.onClick_restart,!1);a.reStart=null;document.getElementById("over").style.display="none";a.init()},randomNum:function(a){return parseInt(Math.random()*a)},paintGround:function(c,b){var d=c.width,e=c.height,f,g,k=c.getContext("2d"),h=a.gSpriteSheets.scene,u=h.getStats(b);for(g=0;g<e;g+=70)for(f=0;f<d;f+=70)k.drawImage(h.img,u.x,u.y,u.w,
u.h,f,g,70,70)},getCentrePoint:function(a,b,d){var e=2*(b[0]-a[0]),f=2*(b[1]-a[1]),g=b[0]*b[0]+b[1]*b[1]-a[0]*a[0]-a[1]*a[1],k=2*(d[0]-b[0]),h=2*(d[1]-b[1]);d=d[0]*d[0]+d[1]*d[1]-b[0]*b[0]-b[1]*b[1];b=(f*d-h*g)/(f*k-h*e);e=(k*g-e*d)/(f*k-h*e);return[b,e,Math.sqrt((b-a[0])*(b-a[0])+(e-a[1])*(e-a[1]))]},getGeoCentre:function(a){var b=a[0][0];a=this.pointEq(a[1][0],b)||this.pointEq(a[1][1],b)?a[2]:a[1];a=this.getMiddle(a);return[(b[0]-a[0])/3+a[0],(b[1]-a[1])/3+a[1]]},getMiddle:function(a){return[(a[0][0]+
a[1][0])/2,(a[0][1]+a[1][1])/2]},reverseEdge:function(a){return[a[1],a[0]]},pointEq:function(a,b){return a[0]==b[0]&&a[1]==b[1]},edgeEq:function(a,b){return this.pointEq(a[0],b[0])&&this.pointEq(a[1],b[1])||this.pointEq(a[0],b[1])&&this.pointEq(a[1],b[0])},isInRange:function(a,b,d){return this.getDistance(a,b)<=d?!0:!1},ok2Draw:function(c,b,d){void 0==d&&(d=a.cfg.Restriction);for(var e=0;e<d.length;e++)if(!a.lang.isOnLeft(d[e],[c,b]))return!1;return!0},getDistance:function(a,b){return Math.sqrt((a[0]-
b[0])*(a[0]-b[0])+(a[1]-b[1])*(a[1]-b[1]))},getNextPos:function(a,b,d,e){var f=this.getDistance(b,d);if(f-1<=e)return d;var g=(d[0]-b[0])*e/f+a[0];a=(d[1]-b[1])*e/f+a[1];return this.getDistance(b,[g,a])>=f?d:[g,a]},getCurDir:function(a,b){var d=b[0]-a[0],e=b[1]-a[1],f=Math.abs(d),g=Math.abs(e);return 0<d&&g<=d?3:0<e&&f<=e?1:0>d&&g<=f?2:4},getCannon:function(a,b,d){var e=this.getDistance(a,b),f=(b[0]-a[0])/e;b=(b[1]-a[1])/e;return[[3*f+a[0],3*b+a[1]],[f*(3+d)+a[0],b*(3+d)+a[1]]]},clearGrass:function(c){for(var b=
0;b<a.grassQueue.length;b++)this.getDistance(c,a.grassQueue[b].position)<=2*a.cfg.buildingR&&(a.grassQueue[b].alive=!1)},ableToBuild:function(c,b){var d=parseInt(c[0]),e=parseInt(c[1]),f;if(null==a.mapData)return!1;if(d+b>=a.cfg.width||0>d-b||e+b>=a.cfg.height||0>e-b)return-1;f=a.mapData[e][d+b];if(a.mapData[e][d-b]!=f||a.mapData[e+b][d]!=f||a.mapData[e-b][d]!=f)return-1;if(0==f){for(d=0;d<a.buildingQueue.length;d++)if(this.getDistance(a.buildingQueue[d].position,c)<=2*b)return-1;for(d=0;d<a.irremovalbeGrassQueue.length;d++)if(30>=
this.getDistance(a.irremovalbeGrassQueue[d].position,c))return-1}else for(d=0;d<a.inBuildingQueue.length;d++)if(this.getDistance(a.inBuildingQueue[d].position,c)<=2*b)return-1;return f+1},showBuildingInfo:function(c){null==c?this.bindingElement(a.panelElement,"<dt>Level</dt><dd> </dd><dt>Damage</dt><dd> </dd><dt>Range</dt><dd> </dd><dt>Shot delay</dt><dd> </dd><dt>Live</dt><dd> </dd><dt>Upgrade cost</dt><dd> </dd>"):(c="<dt>Level</dt><dd>"+c.level+"</dd><dt>Damage</dt><dd>"+c.damage+"</dd><dt>Range</dt><dd>"+
c.range+"</dd><dt>Shot delay</dt><dd>"+c.frequency+"</dd><dt>Live</dt><dd>"+c.live+" / "+c.maxLive+"</dd><dt>Upgrade cost</dt><dd>$ "+(3==c.level?"-":a.cfg.upgradeMapping[c.type][c.level].price)+"</dd>",this.bindingElement(a.panelElement,c))},bindingElement:function(a,b){a.innerHTML=b},setMoney:function(c){a.money=c;this.bindingElement(a.moneyElement,"money : "+a.money)},setWave:function(c){a.wave=c;this.bindingElement(a.waveElement,"wave : "+a.wave)},setScore:function(c){a.score=c;this.bindingElement(a.scoreElement,
"score : "+a.score)},accuracyDestroyer:function(a,b){var d=parseInt(Math.random()*b-b/2),e=parseInt(Math.random()*b-b/2);return[a[0]+d,a[1]+e]},getRandomMonster:function(){var c=parseInt(4*Math.random()+1),c=this.copy(a.cfg.Monsters["monster-"+c]);c.speed=50<=a.wave?c.speed+(.6*Math.random()-.1):40<=a.wave?c.speed+(.5*Math.random()-.1):30<=a.wave?c.speed+(.4*Math.random()-.1):20<=a.wave?c.speed+(.3*Math.random()-.1):c.speed+(.2*Math.random()-.1);c.range+=parseInt(20*Math.random()-10);c.shield=.7<
Math.random()?!0:!1;return new a.monster(a.root,c)},copy:function(a){var b={},d;for(d in a)a.hasOwnProperty(d)&&(b[d]=a[d]);return b},levelUp:function(){if(0!=a.wave){var c,b=8;10>a.wave?c=1.2:10<=a.wave&&20>a.wave?(c=1.15,b=7):20<=a.wave&&30>a.wave?(c=1.1,b=6):30<=a.wave&&40>a.wave?(c=1.05,b=5):(c=1.01,b=parseInt(a.wave/20));0==a.wave%40&&(c=1.3,a.maxNumberOfMonsterPerWave+=1);0==a.wave%10&&(a.maxNumberOfMonsterPerWave+=2);a.cfg.monster_1_base_live=parseInt(a.cfg.monster_1_base_live*c);a.cfg.monster_2_base_live=
parseInt(a.cfg.monster_2_base_live*c);a.cfg.monster_3_base_live=parseInt(a.cfg.monster_3_base_live*c);a.cfg.monster_4_base_live=parseInt(a.cfg.monster_4_base_live*c);a.cfg.monster_1_base_price=parseInt(a.cfg.monster_1_base_price+b);a.cfg.monster_2_base_price=parseInt(a.cfg.monster_2_base_price+b);a.cfg.monster_3_base_price=parseInt(a.cfg.monster_3_base_price+b);a.cfg.monster_4_base_price=parseInt(a.cfg.monster_4_base_price+b)}},getBuilding:function(c,b){var d,e;for(d=0;d<a.buildingQueue.length;d++)if(this.getDistance(a.buildingQueue[d].position,
c)<=b)return a.buildingQueue[d];for(d=0;d<a.inBuildingQueue.length;d++)if(this.getDistance(a.inBuildingQueue[d].position,c)<=b)return a.inBuildingQueue[d];for(e in a.aliveTerminals)if(a.aliveTerminals.hasOwnProperty(e)&&this.getDistance(a.aliveTerminals[e].position,c)<=b)return a.aliveTerminals[e];for(e in a.deadTerminals)if(a.deadTerminals.hasOwnProperty(e)&&this.getDistance(a.deadTerminals[e].position,c)<=b)return a.deadTerminals[e];return null},getSignByCrossProduct:function(a,b){return 0<=a[0]*
b[1]-a[1]*b[0]?1:-1},getAngle360:function(a,b){var d=[a[1][0]-a[0][0],a[1][1]-a[0][1]],e=[b[1][0]-b[0][0],b[1][1]-b[0][1]],f=this.getSignByCrossProduct(d,e);return Math.acos((d[0]*e[0]+d[1]*e[1])/(Math.sqrt(d[0]*d[0]+d[1]*d[1])*Math.sqrt(e[0]*e[0]+e[1]*e[1])))*f},getAngle:function(a,b){var d,e,f;if(this.pointEq(a[0],b[0])||this.pointEq(a[0],b[1]))d=a[0],e=a[1],f=this.pointEq(d,b[0])?b[1]:b[0];else if(this.pointEq(a[1],b[0])||this.pointEq(a[1],b[1]))d=a[1],e=a[0],f=this.pointEq(d,b[0])?b[1]:b[0];else return null;
e=[e[0]-d[0],e[1]-d[1]];d=[f[0]-d[0],f[1]-d[1]];return Math.acos((e[0]*d[0]+e[1]*d[1])/(Math.sqrt(e[0]*e[0]+e[1]*e[1])*Math.sqrt(d[0]*d[0]+d[1]*d[1])))/3.1416*180}}});
_TD.loading.push(function(a){a.createPath=function(c){var b={},d={},e=[],f=[],g=null,k=null,h=document.getElementById("td-canvas").getContext("2d");this.getData=function(b){var c,d,e,f=a.cfg.height,g=a.cfg.width,l=a.lang.Create2DArray(f,g);for(c=1;c<f-1;c++)for(d=1;d<g-1;d++)e=4*c*g+4*d,l[c][d]=0==b[e]&&0==b[e+1]&&0==b[e+2]&&0==b[e+3]?1:0;a.lang.refineMap(l);l[1][1]=2;l[2][1]=2;l.rows=f;l.columns=g;e=[];e.push([1,1,6]);e.push([2,1,6]);this.findPath(l,2,1,e);b=this.findInnerLine(l);c=this.parseQue(e);
d=[];a.lang.drawOutline(h,c);for(e=0;e<b.length;e++)f=this.parseQue(b[e]),d.push(f),a.lang.drawOutline(h,f);a.mapData=l;return[c,d]};this.getData.prototype={findPath:function(b,c,d,e){var f,g,l,k,h;for(l=0;l<a.cfg.Dir.length;l++)for(k=a.cfg.Dir[l],h=0;h<k.length;h++)if(f=k[h][0]+c,g=k[h][1]+d,!(1>c||c>=b.rows-1||1>d||d>=b.columns-1||1!=b[f][g])&&this.checkCross(b,f,g,a.cfg.dirC))return e.push([g,f,k[h][2]]),b[f][g]=2,this.findPath(b,f,g,e);return null},checkCross:function(a,b,c,d){var e,f,g;for(e=
0;e<d.length;e++)if(f=d[e][0]+b,g=d[e][1]+c,!(0>b||b>=a.rows||0>c||c>=a.columns)&&0==a[f][g])return!0;return!1},findInnerLine:function(a){var b=[],c=[],d=!1,e,f;for(e=1;e<a.rows-1;e++)for(f=1;f<a.columns-1;f++)0==a[e][f]&&1==a[e][f+1]?d=!0:d&&1==a[e][f]&&0==a[e][f+1]?d=!1:this.isStartable(a,e,f,c)&&(this.findPath(a,e-1,f+1,c),b.push(c),c=[]);return b},isStartable:function(a,b,c,d){if(1!=a[b][c])return!1;if(void 0!=a[b][c+1]&&0==a[b][c+1])if(void 0!=a[b][c+2]&&0!=a[b][c+2])a[b][c+1]=1;else return a[b][c]=
2,a[b-1][c+1]=2,d.push([c,b,3]),d.push([c+1,b-1,3]),!0;return!1},parseQue:function(a){var b=a[0],c=a[0],d,e,f=0,g=0;if(2>a.length)return null;var k=[];k.push([b[0],b[1]]);for(e=0;e<a.length;e++)d=a[e],d[2]==b[2]?(f+=1,20<f?(k.push([c[0],c[1]]),c=b=d,g=f=0):c=d):(g+=1,c=d,15<f+g?(k.push([c[0],c[1]]),c=b=d,g=f=0):7<g&&(k.push([c[0],c[1]]),c=b=d,g=f=0));k.push([a[0][0],a[0][1]]);return k}};this.cdt=function(b,c){k=this;var d={},e=[],f,e=e.concat(b.slice(0,b.length-1));this.buildEdgeMap(d,b);for(f=0;f<
c.length;f++)this.buildEdgeMap(d,c[f]),e=e.concat(c[f].slice(0,c[f].length-1));for(var g=1E3;0<g&&0<Object.keys(d).length;){g--;var l=Object.keys(d)[0],h=d[l];if(a.lang.pointEq(h[0],h[1]))delete d[l];else{delete d[l];var l=[],q=null,n=[];for(f=0;f<e.length;f++){var m=e[f];a.lang.isOnLeft(h,m)&&n.push(m)}for(f=0;f<n.length;f++){for(var p=n[f],m=[p],p=a.lang.getCentrePoint(h[0],h[1],p),x=0;x<n.length;x++)if(x!=f){var z=n[x],A=a.lang.isInCircle(p,z);if(1==A){m=null;break}else 0==A&&m.push(z)}null!=m&&
(null==q||q[2]>p[2])&&(l=m,q=p)}1<l.length?(console.log("==> Same Circle <=="),console.log(l),console.log(h),this.resolveCircleProblem(h,l,d)):(f=h[0],q=l[0],l=l[0],n=h[1],void 0!=d[[q,f]]||void 0!=d[[f,q]]?(delete d[[q,f]],delete d[[f,q]]):d[[f,q]]=[f,q],void 0!=d[[n,l]]||void 0!=d[[l,n]]?(delete d[[n,l]],delete d[[l,n]]):d[[l,n]]=[l,n],this.processTriangle(h,[f,q],[l,n]))}}};this.cdt.prototype={buildEdgeMap:function(a,c){var d;for(d=0;d<c.length-1;d++)a[[c[d],c[d+1]]]=[c[d],c[d+1]],b[[c[d],c[d+
1]]]=[c[d],c[d+1]],b[[c[d+1],c[d]]]=[c[d+1],c[d]]},processTriangle:function(c,v,k){var r=0,h=[],t=[],l=null;void 0!=b[c]?(r++,h.push(c)):t.push(c);void 0!=b[v]?(r++,h.push(v)):t.push(v);void 0!=b[k]?(r++,h.push(k)):t.push(k);0==r?(l=new this.Tri(t,h,"J"),l.processJunction()):1==r?(l=new this.Tri(t,h,"L"),l.processLinker()):2==r?(l=new this.Tri(t,h,"T"),l.processTerminal(),a.lang.pointEq(l.value.T,[1,1])&&(g=l,console.log("start triangle:"),console.log(l)),f.push(l)):console.log("too many terminal edges!");
e.push(l);for(c=0;c<t.length;c++)v=t[c],void 0==d[v]&&(d[v]=[],d[a.lang.reverseEdge(v)]=[]),d[v].push(l),d[a.lang.reverseEdge(v)].push(l);return l},computeTriAreaByEdges:function(b){var c=b[0][0][0],d=b[0][0][1],e=b[0][1][0],f=b[0][1][1],g;a.lang.pointEq(b[0][0],b[1][0])||a.lang.pointEq(b[0][1],b[1][0])?(g=b[1][1][0],b=b[1][1][1]):(g=b[1][0][0],b=b[1][0][1]);return Math.abs((e-c)*(b-d)-(g-c)*(f-d))/2},Tri:function(b,c,d){this.Inner=b;this.Outer=c;this.Feature=d;this.isVisited=!1;this.value={};this.area=
k.computeTriAreaByEdges(b.concat(c));this.toString=function(){return this.Inner+" "+this.Outer};this.position=null;this.changeFeature=function(b){for(var c=0;c<this.Inner.length;c++)if(a.lang.edgeEq(b,this.Inner[c])){this.Outer.push(this.Inner[c]);this.Inner.splice(c,1);break}1==this.Outer.length?(this.Feature="L",this.processLinker()):2==this.Outer.length?(this.Feature="T",this.processTerminal()):console.log("In changeFeature function: too many terminal edges!")};this.processTerminal=function(){this.value=
{};var b;b=this.Outer[0][0]==this.Outer[1][0]||this.Outer[0][0]==this.Outer[1][1]?this.Outer[0][0]:this.Outer[0][1];this.value.T=b;this.value.M=a.lang.getMiddle(this.Inner[0]);this.value.A=a.lang.getAngle(this.Outer[0],this.Outer[1]);this.position=b};this.processJunction=function(){this.value={};var c=a.lang.getGeoCentre(this.Inner),d=a.lang.getMiddle(this.Inner[0]),e=a.lang.getMiddle(this.Inner[1]),f=a.lang.getMiddle(this.Inner[2]);this.value[this.Inner[0]]=[c,e,this.Inner[1],f,this.Inner[2]];this.value[a.lang.reverseEdge(this.Inner[0])]=
[c,e,this.Inner[1],f,this.Inner[2]];this.value[this.Inner[1]]=[c,d,b[0],f,b[2]];this.value[a.lang.reverseEdge(this.Inner[1])]=[c,d,this.Inner[0],f,this.Inner[2]];this.value[this.Inner[2]]=[c,d,this.Inner[0],e,this.Inner[1]];this.value[a.lang.reverseEdge(this.Inner[2])]=[c,d,this.Inner[0],e,this.Inner[1]];this.position=c};this.processLinker=function(){this.value={};var b=a.lang.getMiddle(this.Inner[0]),c=a.lang.getMiddle(this.Inner[1]);this.value[this.Inner[0]]=[c,this.Inner[1]];this.value[a.lang.reverseEdge(this.Inner[0])]=
[c,this.Inner[1]];this.value[this.Inner[1]]=[b,this.Inner[0]];this.value[a.lang.reverseEdge(this.Inner[1])]=[b,this.Inner[0]];this.position=b}},resolveCircleProblem:function(b,c,d,e){e=[];for(var f=0;f<c.length;f++)e.push([b[0],c[f],a.lang.getAngle(b,[b[0],c[f]])]);e.sort(function(a,b){return b[2]-a[2]});e.push([b[0],b[1],0]);for(f=0;f<e.length-1;f++){c=this.processTriangle([e[f][1],b[0]],[e[f+1][1],e[f][1]],[b[0],e[f+1][1]]);console.log("in circle get a tri:");console.log(c);for(var g=0;g<c.Outer.length;g++)delete d[c.Outer[g]];
for(g=0;g<c.Inner.length;g++){var k=c.Inner[g][0],h=c.Inner[g][1];void 0!=d[[k,h]]||void 0!=d[[h,k]]?(delete d[[k,h]],delete d[[h,k]]):d[[k,h]]=[k,h]}}}};this.trimRedundantTerminalTriangle=function(){for(;0<f.length;){var b=f.shift();if(!(100>b.value.A)){var c=b.Inner[0],e=d[c],e=e[0]==b?e[1]:e[0];console.log("trim this bad triangle!");console.log(b);e.changeFeature(c);"T"==e.Feature&&(console.log("add new terminal tri"),console.log(e),f.push(e));delete d[c];delete d[a.lang.reverseEdge(c)]}}};this.buildPath=
function(b){if(null==b)console.log("failed to find start Triangle");else{var c=[],d=0,e,f=null,g=new this.Node(b.position,b,null,null,"TS");for(c.push(g);0<c.length;){b=c.length;for(var k={};0<b;){b--;e=c.shift();e.depth=d;if("TS"==e.Feature)f=[e.triangle.Inner[0]];else if("J"==e.Feature&&1==e.parentEdge.length)f=e.triangle.value[e.parentEdge],f=[f[2],f[4]];else if("J"==e.Feature&&2==e.parentEdge.length)for(var h=0;h<e.triangle.Inner.length;h++){if(!a.lang.edgeEq(e.triangle.Inner[h],e.parentEdge[0])&&
!a.lang.edgeEq(e.triangle.Inner[h],e.parentEdge[1])){f=[e.triangle.Inner[h]];break}}else if("J"==e.Feature&&3==e.parentEdge.length){"TJ"==e.Feature;this.recordTerminal(e);continue}else console.log("Function<buildPath>: do not push 'T' feature node into queue");for(h=0;h<f.length;h++){var q=this.singlePath(e.triangle,f[h]),n=q[0],m=q[1],q=q[2];if(m==e.triangle){e.Feature="TJ";e.fellow.push(e);e.fellow.push(e);e.pathToFellow.push(n);e.pathToFellow.push(this.copyReversePath(n));this.recordTerminal(e);
break}else if("T"==m.Feature){var p=new this.Node(m.position,m,e,q,"T");e.children.push(p);e.pathToChildren.push(n);p.pathToParent.push(this.copyReversePath(n));m.isVisited=!0;p.depth=d+1;this.recordTerminal(p)}else void 0!=k[m]?(p=k[m],e.children.push(p),e.pathToChildren.push(n),p.pathToParent.push(this.copyReversePath(n)),p.parentnode.push(e),p.parentEdge.push(q)):m.isVisited?(m=k[m],void 0==m?k[e.triangle]=e:(e.fellow.push(m),e.pathToFellow.push(n),m.fellow.push(e),m.pathToFellow.push(this.copyReversePath(n)),
2==e.fellow.length&&(e.Feature="TJ",recordTerminal(e)),2==m.fellow.length&&(m.Feature="TJ",this.recordTerminal(m)))):(p=new this.Node(m.position,m,e,q,"J"),e.children.push(p),e.pathToChildren.push(n),p.pathToParent.push(this.copyReversePath(n)),c.push(p),m.isVisited=!0,k[m]=p)}}d++}return g}};this.buildPath.prototype={Node:function(b,c,d,e,f){this.position=b;this.Feature=f;this.weight=this.depth=0;this.reachable={};this.triangle=c;this.parentEdge=[e];this.parentnode=[d];this.pathToParent=[];this.fellow=
[];this.pathToFellow=[];this.children=[];this.pathToChildren=[];this.toString=function(){return this.position.toString()};this.worthToVisit=function(){if("TA"==this.Feature)return 1;if("undefined"===typeof a.aliveTerminals)return!0;var b=-1,c;for(c in a.aliveTerminals)if(a.aliveTerminals.hasOwnProperty(c))if(0==this.reachable[c])b=0;else if(1==this.reachable[c])return 1;return b}},singlePath:function(b,c){var e=[],f;if("T"==b.Feature||"J"==b.Feature)f=[b.position,a.cfg.speedMapping(b.area)];else return console.log("can not create single path starting from linker triangle"),
null;e.push(f);do b=d[c][0]==b?d[c][1]:d[c][0],f=[a.lang.getMiddle(c),a.cfg.speedMapping(b.area)],e.push(f),"T"==b.Feature||"J"==b.Feature?(f=[b.position,a.cfg.speedMapping(b.area)],e.push(f)):c=b.value[c][1];while("L"==b.Feature);return[e,b,c]},recordTerminal:function(b){a.lang.isOnLeft(a.cfg.taRestriction,b.position)?a.terminalNodePool.push(b):(a.terminalNodePool.unshift(b),b.Feature="TA",b.position[0]-=15,b.position[1]-=10,a.validMap=!0)},copyReversePath:function(a){for(var b=[],c=a.length-1;0<=
c;c--)b.push(a[c]);return b}};this.setPath=function(a){for(var b=0;b<a.length;b++){var c=a[b],d=[];this.dfs4Node(c,c,["parentnode"],1,d);for(var e=0;e<d.length;e++)this.dfs4Node(c,d[e],["parentnode","fellow"],0,[])}};this.dfs4Node=function(a,b,c,d,e){if("TS"!=b.Feature){void 0==b.reachable[a]&&(b.reachable[a]=d,e.push(b));for(var f=0;f<c.length;f++)for(var g=b[c[f]],h=0;h<g.length;h++)void 0==g[h].reachable[a]&&this.dfs4Node(a,g[h],c,d,e)}};this.setWeight=function(a){if("T"==a.Feature||"TJ"==a.Feature)return a.weight=
5,a.weight;if("TA"==a.Feature)return a.weight=10,a.weight;for(var b=0;b<a.children.length;b++)a.weight+=a.pathToChildren[b].length+this.setWeight(a.children[b]);return a.weight};this.pathOutline=new this.getData(c);new this.cdt(this.pathOutline[0],this.pathOutline[1]);this.trimRedundantTerminalTriangle();a.root=new this.buildPath(g);a.validMap?(this.setPath(a.terminalNodePool),this.setWeight(a.root),a.plantMap(a.cfg.density),a.start()):(a.terminalNodePool=[],a.aliveTerminals={},alert("Please connect start point to end point!"),
a.init())}});
_TD.loading.push(function(a){a.strategy=function(a){if("TS"==a.Feature)return[a.children[0],a.pathToChildren[0]];var b=0,b=[],d=function(a,b){var c=a.pop(),d=a.pop(),e,f,r;a.shift();var w=a.shift();r=e=b[d][w].weight+b[c][w].length;for(var t=0;t<a.length;t++)f=b[d][a[t]].weight+b[c][a[t]].length,e+=f,Math.random()<f/e?(r=e-=r,w=a[t]):e-=f;return w};if(0<a.fellow.length&&.1<Math.random()){for(var e=0;e<a.fellow.length;e++)b.push(e);b.push("fellow");b.push("pathToFellow");b.unshift(1);b=d(b,a);return[a.fellow[b],
a.pathToFellow[b]]}if(0<a.children.length){for(e=0;e<a.children.length;e++){var f=a.children[e].worthToVisit();1==f?0==b.length||1!=b[0]?b=[1,e]:b.push(e):0==f?0==b.length||-1==b[0]?b=[0,e]:0==b[0]&&b.push(e):0==b.length?b=[-1,e]:-1==b[0]&&b.push(e)}if(-1==b[0])b=[];else return b.push("children"),b.push("pathToChildren"),b=d(b,a),[a.children[b],a.pathToChildren[b]]}if(0<a.fellow.length){for(e=0;e<a.fellow.length;e++)f=a.fellow[e].worthToVisit(),1==f?0==b.length||1!=b[0]?b=[1,e]:b.push(e):0==f?0==
b.length||-1==b[0]?b=[0,e]:0==b[0]&&b.push(e):0==b.length?b=[-1,e]:-1==b[0]&&b.push(e);if(-1==b[0])b=[];else return b.push("fellow"),b.push("pathToFellow"),b=d(b,a),[a.fellow[b],a.pathToFellow[b]]}if(0<a.parentnode.length){for(e=0;e<a.parentnode.length;e++)f=a.parentnode[e].worthToVisit(),1==f?0==b.length||1!=b[0]?b=[1,e]:b.push(e):0==f?0==b.length||-1==b[0]?b=[0,e]:0==b[0]&&b.push(e):0==b.length?b=[-1,e]:-1==b[0]&&b.push(e);b.push("parentnode");b.push("pathToParent");b=d(b,a);return[a.parentnode[b],
a.pathToParent[b]]}console.log("No available strategy");return null}});
_TD.loading.push(function(a){a.monster=function(c,b){this.position=c.position;this.node=c;this.shield=b.shield;this.type=b.type;this.baseSpeed=this.speed=b.speed;this.range=b.range;this.damage=b.damage;this.cannonType=b.cannonType;this.frequency=b.frequency;this.fire_st=this.target=null;this.setTarget=function(a){this.target=a;this.controlFire()};this.controlFire=function(){null!=this.fire_st&&clearInterval(this.fire_st);if(!(null==this.target||0>=this.target.live)){var b=this;this.fire_st=setInterval(function(){if("bullet_layser"==
b.cannonType)b.fire(b.position,b.target,b.damage,b.cannonType);else{var c=a.lang.accuracyDestroyer(b.target.position,8);b.fire(b.position,c,b.damage,b.cannonType)}},b.frequency)}};this.live=b.live();this.maxLive=b.live();this.price=b.price();this.from=c;this.path=this.to=null;this.probe=0;this.alive=!0;this.dirFrameArray=a.monsterFrame[this.type];this.Dir=this.frame=0;this.move=function(){if(a.pause)return this.setTarget(null),!0;if(0>=this.live)return this.alive=!1,clearInterval(this.fire_st),a.lang.setMoney(a.money+
this.price),a.lang.setScore(a.score+parseInt(this.maxLive/100)),!1;var b=this.findTarget();null==b&&null!=this.target&&this.setTarget(b);if(null!=b)return a.eventQueue.push({position:this.position,type:this.type,spritename:this.dirFrameArray[this.Dir][5],dir:this.Dir}),this.target!=b&&this.setTarget(b),!0;if(null==this.from)return!1;null==this.to&&(b=a.strategy(this.from),this.to=b[0],this.path=b[1],this.probe=1);if(a.lang.pointEq(this.position,this.to.position)||this.probe==this.path.length){if("TA"==
this.to.Feature)return this.alive=!1,this.live=0,!1;this.from=this.to;this.to=null;if("T"==this.from.Feature||"TJ"==this.from.Feature)b=a.aliveTerminals[this.from],void 0!=b&&(b.live=-1);return this.move()}b=a.lang.getCurDir(this.position,this.path[this.probe][0]);this.Dir!=b?(this.frame=0,this.Dir=b):(this.frame++,this.frame%=this.dirFrameArray[this.Dir].length);this.speed=this.baseSpeed*this.path[this.probe-1][1];this.position=a.lang.getNextPos(this.position,this.path[this.probe-1][0],this.path[this.probe][0],
this.speed);a.lang.pointEq(this.position,this.path[this.probe][0])&&this.probe++;a.eventQueue.push({position:this.position,type:this.type,spritename:this.dirFrameArray[this.Dir][this.frame],dir:this.Dir});return!0};this.findTarget=function(){var b,c=this.range,f;if(null!=this.target&&0<this.target.live&&a.lang.getDistance(this.position,this.target.position)<=c)return this.target;for(f in a.aliveTerminals)if(a.aliveTerminals.hasOwnProperty(f)&&(b=a.aliveTerminals[f],a.lang.getDistance(this.position,
b.position)<=c))return b;for(b=0;b<a.inBuildingQueue.length;b++)if(a.lang.isInRange(this.position,a.inBuildingQueue[b].position,c))return a.inBuildingQueue[b];return null};this.fire=function(b,c,f,g){b=new a.bullet({position:b,start:b,end:c,gender:!1,damage:f,type:g});a.bulletQueue.push(b)}}});
_TD.loading.push(function(a){a.drawer=function(c){"Monster"==c.type?a.cfg.monster(a.ucx,c.position):"mouse"==c.type?a.cfg.mouse(a.ucx2,a.uc2,c):"bar"==c.type?a.cfg.bar(a.ucx,c):"monster-1"==c.type?a.cfg.mst1(a.ucx,c):"monster-2"==c.type?a.cfg.mst2(a.ucx,c):"monster-3"==c.type?a.cfg.mst3(a.ucx,c):"monster-4"==c.type?a.cfg.mst4(a.ucx,c):"building-1"==c.type?a.cfg.bld1(a.ucx,c):"building-2"==c.type?a.cfg.bld2(a.ucx,c):"building-3"==c.type?a.cfg.bld3(a.ucx,c):"building-4"==c.type?a.cfg.bld4(a.ucx,c):
"building-5"==c.type?1==c.alive?a.cfg.bld5(a.ucx,c):a.cfg.bld5_2(a.ucx,c):"building-6"==c.type?a.cfg.bld6(a.ucx,c):"bullet_small"==c.type?a.cfg.bullet_small(a.ucx,c):"bullet_middle"==c.type?a.cfg.bullet_middle(a.ucx,c):"bullet_large"==c.type?a.cfg.bullet_large(a.ucx,c):"bullet_layser"==c.type?a.cfg.bullet_layser(a.ucx,c):"bullet_missile"==c.type?a.cfg.bullet_missile(a.ucx,c):"grass"==c.type?a.cfg.grass(a.ucx,c):"game_over"==c.type&&a.cfg.game_over(a.ucx,c)}});
_TD.loading.push(function(a){a.building=function(c,b){this.position=c;this.type=b.type;this.price=b.price;this.level=0;this.frameArray=a.turretFrame[this.type];this.frameIndex=0;this.baseLine=[this.position,[this.position[0]-10,this.position[1]]];this.angle=0;this.maxLive=this.live=b.live;this.frequency=b.frequency;this.range=b.range;this.damage=b.damage;this.upgrade=function(){if(this.level==a.cfg.maxLevel)return!1;var b=a.cfg.upgradeMapping[this.type][this.level];if(a.money<b.price)return!1;a.lang.setMoney(a.money-
b.price);this.price+=b.price;this.level++;this.damage=parseInt(this.damage*b.damage);this.range=parseInt(this.range*b.range);this.live=this.maxLive=parseInt(this.maxLive*b.live);this.frequency=parseInt(this.frequency*b.frequency);"building-6"==this.type&&(this.missileNumber=b.missile);a.lang.showBuildingInfo(this);return!0};this.remove=this.onClick=!1;this.target=null;this.cannonLen=b.cannonLen;this.cannonType=b.cannonType;this.cannonDir=a.lang.getCannon(this.position,[this.position[0]-10,this.position[1]],
this.cannonLen);this.fire_st=null;this.setTarget=function(a){this.target=a;this.controlFire()};this.controlFire=function(){null!=this.fire_st&&clearInterval(this.fire_st);if(null!=this.target){var b=this;this.fire_st=setInterval(function(){if("bullet_missile"==b.cannonType)b.fire(null,null,b.damage,b.cannonType);else if("bullet_layser"==b.cannonType)b.fire(b.cannonDir[1],b.target.position,b.damage,b.cannonType);else{var c=a.lang.accuracyDestroyer(b.target.position,10);b.fire(b.cannonDir[1],c,b.damage,
b.cannonType)}},b.frequency)}};this.cumputeAngle=function(b){this.cannonDir=a.lang.getCannon(this.position,b.position,this.cannonLen);this.angle=a.lang.getAngle360(this.baseLine,[this.position,this.cannonDir[1]])};this.move=function(){if(a.pause)return this.setTarget(null),!0;if(0>=this.live||1==this.remove)return clearInterval(this.fire_st),!1;var b={position:this.position,type:this.type,angle:this.angle,frame:this.frameIndex},c=this.findTarget();null!=c&&(this.cumputeAngle(c),b.frame=this.frameIndex,
this.frameIndex++,this.frameIndex%=this.frameArray.length);this.onClick&&(b.showRange=this.range,a.lang.showBuildingInfo(this));this.target!=c&&this.setTarget(c);a.eventQueue.push(b);return!0};this.findTarget=function(){var b=null,c=this.range,f;if(null!=this.target&&1==this.target.alive&&a.lang.getDistance(this.position,this.target.position)<=c)return this.target;for(var g=0;g<a.monsterQueue.length;g++)f=a.lang.getDistance(this.position,a.monsterQueue[g].position),f<=c&&(c=f,b=a.monsterQueue[g]);
return b};this.fire=function(b,c,f,g){b={position:b,start:b,end:c,gender:!0,damage:f,type:g,hostType:this.type};"bullet_missile"==g?(b.end=this.target,g=new a.missile(b)):("bullet_layser"==g&&(b.end=this.target),g=new a.bullet(b));a.bulletQueue.push(g)}};a.missileBuilding=function(c,b){this.__proto__=new a.building(c,b);this.missileNumber=b.missileNumber;this.curLauncher=[];this.curLaunchPoint=[];this.leftCurb=[this.position,[this.position[0]-a.cfg.buildingR/2,this.position[1]+a.cfg.buildingR]];this.rightCurb=
[this.position,[this.position[0]-a.cfg.buildingR/2,this.position[1]-a.cfg.buildingR]];this.baseLauncher=[[this.position[0]-a.cfg.buildingR/2,this.position[1]+a.cfg.buildingR],[this.position[0]-a.cfg.buildingR/2,this.position[1]-a.cfg.buildingR]];this.baseLaunchPoint=[[this.position[0]-a.cfg.buildingR/2,this.position[1]],[this.position[0]-a.cfg.buildingR/2,this.position[1]-a.cfg.buildingR/3*2],[this.position[0]-a.cfg.buildingR/2,this.position[1]+a.cfg.buildingR/3*2]];this.computeLaunchPointAndCurbRestriction=
function(){var a,b,c,g;for(a=0;2>a;a++)b=this.baseLauncher[a][0]-this.position[0],c=this.baseLauncher[a][1]-this.position[1],g=b*Math.cos(this.angle)-c*Math.sin(this.angle)+this.position[0],b=b*Math.sin(this.angle)+c*Math.cos(this.angle)+this.position[1],this.curLauncher[a]=[g,b];this.leftCurb=[this.position,this.curLauncher[0]];this.rightCurb=[this.position,this.curLauncher[1]];for(a=0;a<this.missileNumber;a++)b=this.baseLaunchPoint[a][0]-this.position[0],c=this.baseLaunchPoint[a][1]-this.position[1],
g=b*Math.cos(this.angle)-c*Math.sin(this.angle)+this.position[0],b=b*Math.sin(this.angle)+c*Math.cos(this.angle)+this.position[1],this.curLaunchPoint[a]=[g,b]};this.move=function(){if(a.pause)return this.setTarget(null),!0;if(0>=this.live||1==this.remove)return clearInterval(this.fire_st),!1;var b=this.findTarget();null!=b&&this.cumputeAngle(b);this.computeLaunchPointAndCurbRestriction();var c={position:this.position,type:this.type,angle:this.angle};this.onClick&&(c.showRange=this.range,a.lang.showBuildingInfo(this));
this.target!=b&&this.setTarget(b);a.eventQueue.push(c);return!0};this.findAllTargets=function(){for(var b=[],c=this.range,f,g,k=0;k<a.monsterQueue.length&&!(b.length>this.missileNumber);k++)g=a.monsterQueue[k],f=a.lang.getDistance(this.position,g.position),f>c||!a.lang.isOnLeft(this.leftCurb,g.position)&&a.lang.isOnLeft(this.rightCurb,g.position)&&b.push(g);return b};this.fire=function(b,c,f,g){b=this.findAllTargets();var k=0,h;for(c=0;c<this.missileNumber;c++)k==b.length&&(k=0),h=b[k++],h=new a.missile({position:this.curLaunchPoint[c],
start:this.curLaunchPoint[c],end:h,gender:!0,damage:f,type:g,hostType:this.type}),a.bulletQueue.push(h)}};a.terminalBuilding=function(c,b,d){this.__proto__=new a.building(c,d);this.type="building-5";this.tid=b;this.firePos=[c[0],c[1]-33];this.upgrade=function(){var b=a.cfg.upgradeMapping[this.type][this.level];if(a.money<b.price)return!1;a.lang.setMoney(a.money-b.price);this.price+=b.price;this.live=this.maxLive*=b.live;a.lang.showBuildingInfo(this);void 0==a.aliveTerminals[this.tid]&&(a.aliveTerminals[this.tid]=
a.deadTerminals[this.tid],a.bloodBarQueue.push(new a.bloodBar(a.aliveTerminals[this.tid])),delete a.deadTerminals[this.tid]);return!0};this.move=function(){if(a.pause)return this.setTarget(null),!0;var b={position:this.position,type:this.type,tid:this.tid.Feature,alive:!0};this.onClick&&(b.showRange=this.range,a.lang.showBuildingInfo(this));if(0>=this.live){clearInterval(this.fire_st);b.alive=!1;a.terminalTmpBuffer.push(b);if(void 0!=a.deadTerminals[this.position])return!1;a.lang.setScore(a.score-
parseInt(this.maxLive/100));"TA"==this.tid.Feature&&(a.GameOver=!0);return!1}var c=this.findTarget();this.target!=c&&this.setTarget(c);a.terminalTmpBuffer.push(b);return!0};this.controlFire=function(){null!=this.fire_st&&clearInterval(this.fire_st);if(null!=this.target){var a=this;this.fire_st=setInterval(function(){a.fire(a.firePos,a.target.position,a.damage,a.cannonType)},a.frequency)}};"TA"==this.tid.Feature&&(this.firePos=[this.position[0],this.position[1]-33])}});
_TD.loading.push(function(a){a.buildingController=function(){this.bld1=document.getElementById("building-1");this.bld2=document.getElementById("building-2");this.bld3=document.getElementById("building-3");this.bld4=document.getElementById("building-4");this.bld6=document.getElementById("building-6");this.ug=document.getElementById("upgrade");this.sl=document.getElementById("sell");this.c=document.getElementById("td-canvas");this.bld1.addEventListener("click",this.onClick_building_1,!1);this.bld2.addEventListener("click",
this.onClick_building_2,!1);this.bld3.addEventListener("click",this.onClick_building_3,!1);this.bld4.addEventListener("click",this.onClick_building_4,!1);this.bld6.addEventListener("click",this.onClick_building_6,!1);this.ug.addEventListener("click",this.onClick_upgrade,!1);this.sl.addEventListener("click",this.onClick_sell,!1);this.c.addEventListener("mousemove",this.onmouseMove,!1);this.c.addEventListener("click",this.onClick,!1)};a.buildingController.prototype={onClick_upgrade:function(c){null!=
a.waitingToChange&&a.waitingToChange.upgrade()},onClick_sell:function(c){null!=a.waitingToChange&&(a.lang.setMoney(a.money+.5*a.waitingToChange.price),a.waitingToChange.onClick=!1,a.waitingToChange.remove=!0,a.waitingToChange=null)},onClick_building_1:function(c){"building-1"==a.waitingToBuild?(a.waitingToBuild=null,a.cfg.clearAll(a.ucx2,a.uc2)):a.waitingToBuild="building-1"},onClick_building_2:function(c){"building-2"==a.waitingToBuild?(a.waitingToBuild=null,a.cfg.clearAll(a.ucx2,a.uc2)):a.waitingToBuild=
"building-2"},onClick_building_3:function(c){"building-3"==a.waitingToBuild?(a.waitingToBuild=null,a.cfg.clearAll(a.ucx2,a.uc2)):a.waitingToBuild="building-3"},onClick_building_4:function(c){"building-4"==a.waitingToBuild?(a.waitingToBuild=null,a.cfg.clearAll(a.ucx2,a.uc2)):a.waitingToBuild="building-4"},onClick_building_6:function(c){"building-6"==a.waitingToBuild?(a.waitingToBuild=null,a.cfg.clearAll(a.ucx2,a.uc2)):a.waitingToBuild="building-6"},onmouseMove:function(c){var b=a.uc2.getBoundingClientRect(),
d=c.clientX-b.left;c=c.clientY-b.top;null!=a.waitingToBuild&&(b={position:[d,c],type:"mouse",buildable:!0},-1==a.lang.ableToBuild([d,c],a.cfg.buildingR)&&(b.buildable=!1),a.drawer(b))},onClick:function(c){var b=a.uc2.getBoundingClientRect(),d=c.clientX-b.left,e=c.clientY-b.top;c=a.lang.ableToBuild([d,e],a.cfg.buildingR);null!=a.waitingToBuild&&-1!=c?(b=a.cfg.Buildings[a.waitingToBuild],a.money>=b.price&&(a.lang.setMoney(a.money-b.price),a.waitingToBuild=null,a.cfg.clearAll(a.ucx2,a.uc2),a.lang.clearGrass([d,
e]),"building-6"==b.type?d=new a.missileBuilding([d,e],b):(d=new a.building([d,e],b),b.angle=0),b.position=d.position,b.frame=0,a.lang.showBuildingInfo(d),a.drawer(b),1==c?a.buildingQueue.push(d):(a.inBuildingQueue.push(d),a.bloodBarQueue.push(new a.bloodBar(d))))):null==a.waitingToBuild&&(d=a.lang.getBuilding([d,e],a.cfg.buildingR),null!=d?(null!=a.waitingToChange&&(a.waitingToChange.onClick=!1),a.waitingToChange=d,a.lang.showBuildingInfo(d),d.onClick=!0):null!=a.waitingToChange&&(a.waitingToChange.onClick=
!1,a.waitingToChange=null,a.lang.showBuildingInfo(null)))}}});
_TD.loading.push(function(a){a.bullet=function(c){this.position=c.position;this.origin=c.start;this.target=c.end;this.type=c.type;this.damage=c.damage;this.gender=c.gender;this.speed=a.cfg.Arsenal[this.type].speed;this.range=a.cfg.Arsenal[this.type].damageRange;this.exploding=a.explodeFrame[this.type];this.index=0;this.hostType=c.hostType;this.move=function(){if("bullet_layser"==this.type){var b={position:this.target.position,origin:this.origin,type:this.type,hostType:this.hostType};this.makeDamage();
a.eventQueue.push(b);return!1}if(1==a.lang.pointEq(this.target,this.position))return this.index<this.exploding.length?(b={position:this.position,type:this.type,exploding:this.exploding[this.index],hostType:this.hostType},this.index++,a.eventQueue.push(b),!0):!1;this.position=b=a.lang.getNextPos(this.position,this.origin,this.target,this.speed);b={position:b,type:this.type,hostType:this.hostType};1==a.lang.pointEq(this.target,this.position)&&(this.makeDamage(),b.exploding=this.exploding[this.index],
this.index++);a.eventQueue.push(b);return!0};this.makeDamage=function(){if("bullet_layser"==this.type)this.target.live=void 0!=this.target.shield&&1==this.target.shield?this.target.live-1.5*this.damage:this.target.live-this.damage;else{var b,c,e;if(1==this.gender)for(b=0;b<a.monsterQueue.length;b++)c=a.monsterQueue[b],e=this.target,"bullet_missile"==this.type&&(e=this.position),a.lang.getDistance(e,c.position)<=this.range&&(c.live=1==c.shield?"bullet_missile"==this.type?c.live-.3*this.damage:"bullet_large"==
this.type?c.live-.5*this.damage:"bullet_middle"==this.type?c.live-.9*this.damage:c.live-this.damage:c.live-this.damage);else{for(b=0;b<a.inBuildingQueue.length;b++)c=a.inBuildingQueue[b],a.lang.getDistance(this.target,c.position)<=this.range&&(c.live-=this.damage);for(e in a.aliveTerminals)a.aliveTerminals.hasOwnProperty(e)&&(c=a.aliveTerminals[e],a.lang.getDistance(this.target,c.position)<=this.range&&(c.live-=this.damage))}}}};a.missile=function(c){this.__proto__=new a.bullet(c);this.track=[];this.count=
15;this.hit=!1;this.curTargetPosition=this.target.position;this.move=function(){!this.hit&&void 0!=this.target&&null!=this.target&&0<this.target.live&&(this.curTargetPosition=this.target.position);if(1==a.lang.pointEq(this.curTargetPosition,this.position)){if(this.index<this.exploding.length){this.track.shift();var b={position:this.curTargetPosition,type:this.type,exploding:this.exploding[this.index],track:this.track};this.index++;a.eventQueue.push(b);return!0}return!1}b=a.lang.getNextPos(this.position,
this.position,this.curTargetPosition,this.speed);this.track.push([this.position,b]);this.position=b;this.track.length>this.count&&this.track.shift();b={position:this.curTargetPosition,type:this.type,track:this.track,catnon:500<this.damage};1==a.lang.pointEq(this.curTargetPosition,this.position)&&(this.hit=!0,this.makeDamage(),b.exploding=this.exploding[this.index],this.index++);a.eventQueue.push(b);return!0}}});
_TD.loading.push(function(a){a.createMap=function(){a.uc.width=500;a.uc.height=500;a.uc2.width=500;a.uc2.height=500;a.uc0.width=500;a.uc0.height=500;this.getRawMapFromStroke=function(){this.mousedown=!1;this.oldy=this.oldx=null;this.height=a.cfg.height;this.width=a.cfg.width;this.c=a.canvasBody;this.cx=a.canvasBody.getContext("2d");this.u=a.undoBody;this.r=a.redoBody;this.s=a.submitBody;this.history=[];this.index=-1;this._init()};this.getRawMapFromStroke.prototype={setupCanvas:function(){this.c.height=
this.height;this.c.width=this.width;this.cx.lineWidth=25;this.cx.lineCap="round";this.cx.strokeStyle="rgba(0, 0, 0, 1)"},onmousedown:function(c){a.map.rawMap.mousedown=!0;c.preventDefault()},onmouseup:function(c){var b=a.map.rawMap;b.mousedown=!1;for(var d=b.cx.getImageData(0,0,b.width,b.height);b.history.length>b.index+1;)b.history.pop();b.history.push(d);b.index++;b.oldx=-1;b.oldy=-1;c.preventDefault()},onmouseout:function(c){var b=a.map.rawMap;if(0!=b.mousedown){b.mousedown=!1;for(var d=b.cx.getImageData(0,
0,b.width,b.height);b.history.length>b.index+1;)b.history.pop();b.history.push(d);b.index++;b.oldx=-1;b.oldy=-1;c.preventDefault()}},onmousemove:function(c){var b=a.map.rawMap,d=b.c.getBoundingClientRect(),e=c.clientX-d.left;c=c.clientY-d.top;b.mousedown&&a.lang.ok2Draw(e,c,a.cfg.Restriction)&&b.paint(e,c)},paint:function(c,b){var d=a.map.rawMap;0<d.oldx&&0<d.oldy&&(d.cx.globalCompositeOperation="destination-out",d.cx.beginPath(),d.cx.moveTo(d.oldx,d.oldy),d.cx.lineTo(c,b),d.cx.stroke(),d.cx.closePath());
d.oldx=c;d.oldy=b},onClickUndo:function(){var c=a.map.rawMap;if(0<c.index){c.index--;var b=c.history[c.index];c.cx.clearRect(0,0,c.width,c.height);c.cx.putImageData(b,0,0)}},onClickRedo:function(){var c=a.map.rawMap;if(c.index+1<c.history.length){c.index++;var b=c.history[c.index];c.cx.clearRect(0,0,c.width,c.height);c.cx.putImageData(b,0,0)}},onClickSubmit:function(){var c=a.map.rawMap;c.c.removeEventListener("mousedown",c.onmousedown,!1);c.c.removeEventListener("mouseup",c.onmouseup,!1);c.c.removeEventListener("mousemove",
c.onmousemove,!1);c.c.removeEventListener("mouseout",c.onmouseout,!1);c.u.removeEventListener("click",c.onClickUndo,!1);c.r.removeEventListener("click",c.onClickRedo,!1);c.s.removeEventListener("click",c.onClickSubmit,!1);document.getElementById("post").style.display="block";document.getElementById("pre").style.display="none";document.getElementById("run").style.display="block";document.getElementById("pause").style.display="none";a.rawMapData=c.history[c.index].data;a.path=new a.createPath(a.rawMapData)},
preDraw:function(){this.cx.clearRect(0,0,this.cx.width,this.cx.height);a.lang.paintGround(a.uc0,"ground_02.png");a.lang.paintGround(this.c,"ground_01.png");this.cx.beginPath();this.cx.strokeStyle="rgba(0, 0, 0, 1)";this.cx.globalCompositeOperation="destination-out";this.cx.lineWidth=30;this.cx.moveTo(0,0);this.cx.lineTo(60,60);this.cx.stroke();this.cx.moveTo(this.width,this.height);this.cx.lineTo(this.width-60,this.height-60);this.cx.stroke();this.cx.closePath()},_init:function(){this.setupCanvas();
this.preDraw();var a=this.cx.getImageData(0,0,this.width,this.height);this.history.push(a);this.index=0;this.c.addEventListener("mousedown",this.onmousedown,!1);this.c.addEventListener("mouseup",this.onmouseup,!1);this.c.addEventListener("mousemove",this.onmousemove,!1);this.c.addEventListener("mouseout",this.onmouseout,!1);this.u.addEventListener("click",this.onClickUndo,!1);this.r.addEventListener("click",this.onClickRedo,!1);this.s.addEventListener("click",this.onClickSubmit,!1)}};this.rawMap=
new this.getRawMapFromStroke}});_TD.loading.push(function(a){a.buildNextWave=function(){a.waitingForNextWave=!1;var c=a.maxNumberOfMonsterPerWave,b=null,d,e=function(){if(0>=c)clearTimeout(b);else{c--;var f=a.lang.getRandomMonster();a.monsterQueue.push(f);f=new a.bloodBar(f);a.bloodBarQueue.push(f);d=parseInt(500*Math.random())+1E3;b=setTimeout(function(){e()},d)}};e()}});
_TD.loading.push(function(a){a.bloodBar=function(c){this.host=c;this.shield=void 0==c.shield?!1:c.shield;this.move=function(){if(void 0==this.host||null==this.host||0>=this.host.live||void 0!=this.host.remove&&this.host.remove)return!1;var b=this.host.position[0]-10,c=this.host.position[0]+10;posY=this.host.position[1]-11;posRx=18*this.host.live/this.host.maxLive+b+1;"building-5"==this.host.type&&(posY-=37);"o"==this.host.type[1]&&(posY-=17);a.eventQueue.push({type:"bar",position:[[b,posY],[c,posY]],
positionIn:[[b+1,posY],[posRx,posY]],shield:this.shield});return!0}}});
_TD.loading.push(function(a){a.gameOver=function(){a.bldCtrl.bld1.removeEventListener("click",a.bldCtrl.onClick_building_1,!1);a.bldCtrl.bld2.removeEventListener("click",a.bldCtrl.onClick_building_2,!1);a.bldCtrl.bld3.removeEventListener("click",a.bldCtrl.onClick_building_3,!1);a.bldCtrl.bld4.removeEventListener("click",a.bldCtrl.onClick_building_4,!1);a.bldCtrl.bld6.removeEventListener("click",a.bldCtrl.onClick_building_6,!1);a.runner.removeEventListener("click",a.onClick_runner,!1);a.pauseElement.removeEventListener("click",
a.onClick_pause,!1);a.bldCtrl.ug.removeEventListener("click",a.bldCtrl.onClick_upgrade,!1);a.bldCtrl.sl.removeEventListener("click",a.bldCtrl.onClick_sell,!1);a.bldCtrl.c.removeEventListener("mousemove",a.bldCtrl.onmouseMove,!1);a.bldCtrl.c.removeEventListener("click",a.bldCtrl.onClick,!1);for(var c,b;0<a.monsterQueue.length;)b=a.monsterQueue.shift(),null!=b.fire_st&&clearTimeout(b.fire_st);for(;0<a.buildingQueue.length;)b=a.buildingQueue.shift(),null!=b.fire_st&&clearTimeout(b.fire_st);for(;0<a.inBuildingQueue.length;)b=
a.inBuildingQueue.shift(),null!=b.fire_st&&clearTimeout(b.fire_st);for(c in a.aliveTerminals)a.aliveTerminals.hasOwnProperty(c)&&(b=a.aliveTerminals[c],null!=b.fire_st&&clearTimeout(b.fire_st),delete a.aliveTerminals[c]);for(c in a.deadTerminals)a.deadTerminals.hasOwnProperty(c)&&(b=a.deadTerminals[c],null!=b.fire_st&&clearTimeout(b.fire_st),delete a.deadTerminals[c]);a.eventQueue=[];a.bulletQueue=[];a.bloodBarQueue=[];a.terminalNodePool=[];a.maxNumberOfMonsterPerWave=a.cfg.maxNumberOfMonsterPerWave;
a.money=a.cfg.money;a.GameOver=!1;a.waitingForNextWave=!1;a.pause=!1;a.root=null;a.validMap=!1;a.beforeRun=!0;a.waitingToBuild=null;a.waitingToChange=null;a.cfg.monster_1_base_live=125;a.cfg.monster_2_base_live=150;a.cfg.monster_3_base_live=175;a.cfg.monster_4_base_live=200;a.cfg.monster_1_base_price=10;a.cfg.monster_2_base_price=12;a.cfg.monster_3_base_price=15;a.cfg.monster_4_base_price=20;a.drawer({type:"game_over",score:a.score,wave:a.wave});a.score=0;a.wave=0;document.getElementById("post").style.display=
"none";document.getElementById("pre").style.display="none";document.getElementById("over").style.display="block";a.reStart=document.getElementById("restart");a.reStart.addEventListener("click",a.lang.onClick_restart,!1)}});
_TD.loading.push(function(a){a.plantMap=function(c){for(var b=a.sceneFrame.grass,d=[],e,f=function(){var a=Math.random();return.7<a?parseInt(12*Math.random()):.5>a?parseInt(4*Math.random()):5},g=function(b){if(1==a.lang.ableToBuild(b,a.cfg.buildingR)){for(e=0;e<d.length;e++)if(a.lang.getDistance(d[e].position,b)<2*a.cfg.buildingR)return!1;return!0}return!1},k=0,h;0<c;){c--;k=5;for(h=null;0<k&&(k--,h=[parseInt(a.cfg.width*Math.random()),parseInt(a.cfg.height*Math.random())],!g(h));)h=null;null!=h&&
(k=f(),h={type:"grass",position:h,spritename:b[k],alive:!0},8==k||9==k?a.irremovalbeGrassQueue.push(h):a.grassQueue.push(h),d.push(h))}}});
_TD.loading.push(function(a){a.spriteSheetHandler=function(){this.init=function(c){if("monster"==c.type){c=a.monsterTypes;var b;for(b=0;b<c.length;b++){var d=new this.SpriteSheetClass(c[b]);d.load(a.monsterSpriteSource);d.parseAtlasDefinition(zombieJSON);a.monsterFrame[c[b]]=this.monsterNameGenerator(3*b+1)}}else if("explode"==c.type)for(c=new this.SpriteSheetClass("explode"),c.load(a.explodeSpriteSource),c.parseAtlasDefinition(explodeJSON),c=a.bulletTypes,b=0;b<c.length;b++)a.explodeFrame[c[b]]=
this.explodeNameGenerator(c[b]);else"scene"==c.type?(c=new this.SpriteSheetClass("scene"),c.load(a.sceneSpriteSource),c.parseAtlasDefinition(sceneJSON),a.sceneFrame.grass=this.sceneNameGenerator("grass",14),a.sceneFrame.ground=this.sceneNameGenerator("ground",2),a.sceneFrame.tower=this.sceneNameGenerator("tower",3),c.img.onload=function(){console.log("IMAGEs!!!")}):"turret"==c.type&&(c=new this.SpriteSheetClass("turret"),c.load(a.turretSpriteSource),c.parseAtlasDefinition(turretJSON),a.turretFrame["building-1"]=
"turret_01_1.png turret_01_1.png turret_01_1.png turret_01_2.png turret_01_2.png turret_01_2.png turret_01_3.png turret_01_3.png turret_01_3.png".split(" "),a.turretFrame["building-2"]=["turret_02.png"],a.turretFrame["building-3"]=["turret_03.png"],a.turretFrame["building-4"]=["turret_04.png"],a.turretFrame["building-6"]=["turret_06.png"])};this.monsterNameGenerator=function(a){a=parseInt(a);if("NaN"==a)return null;a=[10>a?"0"+a:a,10>a+1?"0"+(a+1):a+1,10>a+2?"0"+(a+2):a+2];var b={},d,e,f;for(e=1;5>
e;e++){d=[];for(f=0;3>f;f++)d.push("0"+e+"_"+a[f]+".png"),d.push("0"+e+"_"+a[f]+".png"),d.push("0"+e+"_"+a[f]+".png");d.push("0"+e+"_"+a[1]+".png");d.push("0"+e+"_"+a[1]+".png");d.push("0"+e+"_"+a[1]+".png");b[e]=d}return b};this.sceneNameGenerator=function(a,b){for(var d=[],e=1;e<=b;e++)d.push(a+"_"+(10>e?"0"+e:e)+".png");return d};this.explodeNameGenerator=function(a){return"bullet_small"==a?["01_01.png","01_02.png","01_03.png","01_04.png","01_05.png"]:"bullet_middle"==a?"02_01.png 02_02.png 02_03.png 02_04.png 02_05.png 02_06.png 02_07.png 02_08.png 02_09.png 02_10.png 02_11.png".split(" "):
"bullet_large"==a?"03_01.png 03_02.png 03_03.png 03_04.png 03_05.png 03_06.png 03_07.png 03_08.png 03_9.png 03_10.png 03_11.png 03_12.png 03_13.png".split(" "):"bullet_missile"==a?"06_01.png 06_02.png 06_03.png 06_04.png 06_05.png 06_06.png 06_07.png 06_08.png".split(" "):null};this.SpriteSheetClass=function(c){this.type=c;this.img=null;this.url="";this.sprites=[];this.dirList=null;this.load=function(b){this.url=b;var d=new Image;d.src=b;this.img=d;a.gSpriteSheets[c]=this};this.defSprite=function(a,
c,e,f,g,k,h){this.sprites.push({id:a,x:c,y:e,w:f,h:g,cx:null==k?0:k,cy:null==h?0:h})};this.parseAtlasDefinition=function(a){a=a.frames;for(var c in a){var e=a[c],f=-.5*e.frame.w,g=-.5*e.frame.h;if(1==e.trimmed)var g=e.sourceSize,k=e.spriteSourceSize,f=k.x-.5*g.w,g=k.y-.5*g.h;this.defSprite(c,e.frame.x,e.frame.y,e.frame.w,e.frame.h,f,g)}};this.getStats=function(a){for(var c=0;c<this.sprites.length;c++)if(this.sprites[c].id==a)return this.sprites[c];return null};this.toString=function(){return this.type}}};
a.drawSprite=function(c,b,d,e,f){var g=a.gSpriteSheets[b];if(null==g)return!1;d=g.getStats(d);if(null==d)return!1;var k=d.cx,h=d.cy;"o"==b[1]?c.drawImage(g.img,d.x,d.y,d.w,d.h,e+k,f+h-10,d.w,d.h):c.drawImage(g.img,d.x,d.y,d.w,d.h,e+k,f+h,d.w,d.h)}});
explodeJSON={frames:{"01_01.png":{frame:{x:93,y:502,w:6,h:6},rotated:!1,trimmed:!0,spriteSourceSize:{x:27,y:28,w:6,h:6},sourceSize:{w:60,h:60},pivot:{x:.5,y:.5}},"01_02.png":{frame:{x:174,y:169,w:10,h:10},rotated:!1,trimmed:!0,spriteSourceSize:{x:25,y:25,w:10,h:10},sourceSize:{w:60,h:60},pivot:{x:.5,y:.5}},"01_03.png":{frame:{x:45,y:487,w:17,h:17},rotated:!1,trimmed:!0,spriteSourceSize:{x:22,y:22,w:17,h:17},sourceSize:{w:60,h:60},pivot:{x:.5,y:.5}},"01_04.png":{frame:{x:64,y:487,w:17,h:17},rotated:!1,
trimmed:!0,spriteSourceSize:{x:22,y:22,w:17,h:17},sourceSize:{w:60,h:60},pivot:{x:.5,y:.5}},"01_05.png":{frame:{x:83,y:487,w:13,h:13},rotated:!1,trimmed:!0,spriteSourceSize:{x:26,y:26,w:13,h:13},sourceSize:{w:60,h:60},pivot:{x:.5,y:.5}},"02_01.png":{frame:{x:83,y:502,w:8,h:8},rotated:!1,trimmed:!0,spriteSourceSize:{x:26,y:26,w:8,h:8},sourceSize:{w:60,h:60},pivot:{x:.5,y:.5}},"02_02.png":{frame:{x:189,y:69,w:12,h:12},rotated:!1,trimmed:!0,spriteSourceSize:{x:24,y:24,w:12,h:12},sourceSize:{w:60,h:60},
pivot:{x:.5,y:.5}},"02_03.png":{frame:{x:25,y:487,w:18,h:18},rotated:!1,trimmed:!0,spriteSourceSize:{x:21,y:21,w:18,h:18},sourceSize:{w:60,h:60},pivot:{x:.5,y:.5}},"02_04.png":{frame:{x:1,y:487,w:22,h:23},rotated:!1,trimmed:!0,spriteSourceSize:{x:19,y:19,w:22,h:23},sourceSize:{w:60,h:60},pivot:{x:.5,y:.5}},"02_05.png":{frame:{x:159,y:259,w:27,h:28},rotated:!1,trimmed:!0,spriteSourceSize:{x:17,y:16,w:27,h:28},sourceSize:{w:60,h:60},pivot:{x:.5,y:.5}},"02_06.png":{frame:{x:128,y:474,w:33,h:33},rotated:!1,
trimmed:!0,spriteSourceSize:{x:14,y:14,w:33,h:33},sourceSize:{w:60,h:60},pivot:{x:.5,y:.5}},"02_07.png":{frame:{x:163,y:474,w:33,h:32},rotated:!1,trimmed:!0,spriteSourceSize:{x:14,y:14,w:33,h:32},sourceSize:{w:60,h:60},pivot:{x:.5,y:.5}},"02_08.png":{frame:{x:232,y:470,w:32,h:30},rotated:!1,trimmed:!0,spriteSourceSize:{x:14,y:15,w:32,h:30},sourceSize:{w:60,h:60},pivot:{x:.5,y:.5}},"02_09.png":{frame:{x:94,y:259,w:31,h:28},rotated:!1,trimmed:!0,spriteSourceSize:{x:15,y:16,w:31,h:28},sourceSize:{w:60,
h:60},pivot:{x:.5,y:.5}},"02_10.png":{frame:{x:127,y:259,w:30,h:28},rotated:!1,trimmed:!0,spriteSourceSize:{x:15,y:16,w:30,h:28},sourceSize:{w:60,h:60},pivot:{x:.5,y:.5}},"02_11.png":{frame:{x:98,y:474,w:28,h:26},rotated:!1,trimmed:!0,spriteSourceSize:{x:16,y:18,w:28,h:26},sourceSize:{w:60,h:60},pivot:{x:.5,y:.5}},"03_01.png":{frame:{x:241,y:132,w:45,h:42},rotated:!1,trimmed:!1,spriteSourceSize:{x:0,y:0,w:45,h:42},sourceSize:{w:45,h:42},pivot:{x:.5,y:.5}},"03_02.png":{frame:{x:244,y:176,w:50,h:48},
rotated:!1,trimmed:!1,spriteSourceSize:{x:0,y:0,w:50,h:48},sourceSize:{w:50,h:48},pivot:{x:.5,y:.5}},"03_03.png":{frame:{x:240,y:254,w:54,h:54},rotated:!1,trimmed:!1,spriteSourceSize:{x:0,y:0,w:54,h:54},sourceSize:{w:54,h:54},pivot:{x:.5,y:.5}},"03_04.png":{frame:{x:241,y:69,w:60,h:61},rotated:!1,trimmed:!1,spriteSourceSize:{x:0,y:0,w:60,h:61},sourceSize:{w:60,h:61},pivot:{x:.5,y:.5}},"03_05.png":{frame:{x:189,y:1,w:66,h:66},rotated:!1,trimmed:!1,spriteSourceSize:{x:0,y:0,w:66,h:66},sourceSize:{w:66,
h:66},pivot:{x:.5,y:.5}},"03_06.png":{frame:{x:175,y:289,w:63,h:61},rotated:!1,trimmed:!0,spriteSourceSize:{x:0,y:0,w:63,h:61},sourceSize:{w:64,h:63},pivot:{x:.5,y:.5}},"03_07.png":{frame:{x:174,y:100,w:65,h:67},rotated:!1,trimmed:!0,spriteSourceSize:{x:0,y:0,w:65,h:67},sourceSize:{w:67,h:69},pivot:{x:.5,y:.5}},"03_08.png":{frame:{x:171,y:181,w:71,h:71},rotated:!1,trimmed:!0,spriteSourceSize:{x:0,y:0,w:71,h:71},sourceSize:{w:72,h:73},pivot:{x:.5,y:.5}},"03_9.png":{frame:{x:94,y:181,w:75,h:76},rotated:!1,
trimmed:!0,spriteSourceSize:{x:0,y:0,w:75,h:76},sourceSize:{w:77,h:77},pivot:{x:.5,y:.5}},"03_10.png":{frame:{x:94,y:100,w:78,h:79},rotated:!1,trimmed:!1,spriteSourceSize:{x:0,y:0,w:78,h:79},sourceSize:{w:78,h:79},pivot:{x:.5,y:.5}},"03_11.png":{frame:{x:90,y:388,w:80,h:84},rotated:!1,trimmed:!1,spriteSourceSize:{x:0,y:0,w:80,h:84},sourceSize:{w:80,h:84},pivot:{x:.5,y:.5}},"03_12.png":{frame:{x:1,y:300,w:86,h:92},rotated:!1,trimmed:!1,spriteSourceSize:{x:0,y:0,w:86,h:92},sourceSize:{w:86,h:92},pivot:{x:.5,
y:.5}},"03_13.png":{frame:{x:89,y:300,w:84,h:86},rotated:!1,trimmed:!1,spriteSourceSize:{x:0,y:0,w:84,h:86},sourceSize:{w:84,h:86},pivot:{x:.5,y:.5}},"06_01.png":{frame:{x:198,y:470,w:32,h:31},rotated:!1,trimmed:!0,spriteSourceSize:{x:35,y:34,w:32,h:31},sourceSize:{w:100,h:100},pivot:{x:.5,y:.5}},"06_02.png":{frame:{x:257,y:1,w:60,h:61},rotated:!1,trimmed:!0,spriteSourceSize:{x:20,y:19,w:60,h:61},sourceSize:{w:100,h:100},pivot:{x:.5,y:.5}},"06_03.png":{frame:{x:172,y:388,w:76,h:80},rotated:!1,trimmed:!0,
spriteSourceSize:{x:12,y:9,w:76,h:80},sourceSize:{w:100,h:100},pivot:{x:.5,y:.5}},"06_04.png":{frame:{x:1,y:394,w:87,h:91},rotated:!1,trimmed:!0,spriteSourceSize:{x:7,y:4,w:87,h:91},sourceSize:{w:100,h:100},pivot:{x:.5,y:.5}},"06_05.png":{frame:{x:93,y:1,w:94,h:97},rotated:!1,trimmed:!0,spriteSourceSize:{x:3,y:3,w:94,h:97},sourceSize:{w:100,h:100},pivot:{x:.5,y:.5}},"06_06.png":{frame:{x:1,y:202,w:91,h:96},rotated:!1,trimmed:!0,spriteSourceSize:{x:5,y:3,w:91,h:96},sourceSize:{w:100,h:100},pivot:{x:.5,
y:.5}},"06_07.png":{frame:{x:1,y:102,w:91,h:98},rotated:!1,trimmed:!0,spriteSourceSize:{x:4,y:1,w:91,h:98},sourceSize:{w:100,h:100},pivot:{x:.5,y:.5}},"06_08.png":{frame:{x:1,y:1,w:90,h:99},rotated:!1,trimmed:!0,spriteSourceSize:{x:6,y:1,w:90,h:99},sourceSize:{w:100,h:100},pivot:{x:.5,y:.5}}},meta:{app:"http://www.codeandweb.com/texturepacker",version:"1.0",image:"explode.png",format:"RGBA8888",size:{w:512,h:512},scale:"1",smartupdate:"$TexturePacker:SmartUpdate:50831b6d4189548a20836f168e97f252:9ccd415734d1cf3e4d04471aa818a1cb:133b2ce0197d17ada5c779ea3e08f404$"}};
zombieJSON={frames:{"01_01.png":{frame:{x:110,y:67,w:23,h:31},rotated:!1,trimmed:!1,spriteSourceSize:{x:0,y:0,w:23,h:31},sourceSize:{w:23,h:31},pivot:{x:.5,y:.5}},"01_02.png":{frame:{x:1,y:141,w:23,h:33},rotated:!1,trimmed:!1,spriteSourceSize:{x:0,y:0,w:23,h:33},sourceSize:{w:23,h:33},pivot:{x:.5,y:.5}},"01_03.png":{frame:{x:78,y:171,w:24,h:31},rotated:!1,trimmed:!1,spriteSourceSize:{x:0,y:0,w:24,h:31},sourceSize:{w:24,h:31},pivot:{x:.5,y:.5}},"01_04.png":{frame:{x:79,y:135,w:24,h:31},rotated:!1,
trimmed:!1,spriteSourceSize:{x:0,y:0,w:24,h:31},sourceSize:{w:24,h:31},pivot:{x:.5,y:.5}},"01_05.png":{frame:{x:1,y:71,w:24,h:33},rotated:!1,trimmed:!1,spriteSourceSize:{x:0,y:0,w:24,h:33},sourceSize:{w:24,h:33},pivot:{x:.5,y:.5}},"01_06.png":{frame:{x:82,y:67,w:26,h:31},rotated:!1,trimmed:!1,spriteSourceSize:{x:0,y:0,w:26,h:31},sourceSize:{w:26,h:31},pivot:{x:.5,y:.5}},"01_07.png":{frame:{x:25,y:211,w:30,h:32},rotated:!1,trimmed:!1,spriteSourceSize:{x:0,y:0,w:30,h:32},sourceSize:{w:30,h:32},pivot:{x:.5,
y:.5}},"01_08.png":{frame:{x:1,y:1,w:31,h:33},rotated:!1,trimmed:!1,spriteSourceSize:{x:0,y:0,w:31,h:33},sourceSize:{w:31,h:33},pivot:{x:.5,y:.5}},"01_09.png":{frame:{x:30,y:36,w:32,h:31},rotated:!1,trimmed:!1,spriteSourceSize:{x:0,y:0,w:32,h:31},sourceSize:{w:32,h:31},pivot:{x:.5,y:.5}},"01_10.png":{frame:{x:34,y:1,w:31,h:31},rotated:!1,trimmed:!1,spriteSourceSize:{x:0,y:0,w:31,h:31},sourceSize:{w:31,h:31},pivot:{x:.5,y:.5}},"01_11.png":{frame:{x:1,y:36,w:27,h:33},rotated:!1,trimmed:!1,spriteSourceSize:{x:0,
y:0,w:27,h:33},sourceSize:{w:27,h:33},pivot:{x:.5,y:.5}},"01_12.png":{frame:{x:27,y:105,w:31,h:31},rotated:!1,trimmed:!1,spriteSourceSize:{x:0,y:0,w:31,h:31},sourceSize:{w:31,h:31},pivot:{x:.5,y:.5}},"02_01.png":{frame:{x:182,y:67,w:19,h:31},rotated:!1,trimmed:!1,spriteSourceSize:{x:0,y:0,w:19,h:31},sourceSize:{w:19,h:31},pivot:{x:.5,y:.5}},"02_02.png":{frame:{x:25,y:176,w:20,h:33},rotated:!1,trimmed:!1,spriteSourceSize:{x:0,y:0,w:20,h:33},sourceSize:{w:20,h:33},pivot:{x:.5,y:.5}},"02_03.png":{frame:{x:130,
y:133,w:20,h:31},rotated:!1,trimmed:!1,spriteSourceSize:{x:0,y:0,w:20,h:31},sourceSize:{w:20,h:31},pivot:{x:.5,y:.5}},"02_04.png":{frame:{x:27,y:71,w:20,h:32},rotated:!1,trimmed:!1,spriteSourceSize:{x:0,y:0,w:20,h:32},sourceSize:{w:20,h:32},pivot:{x:.5,y:.5}},"02_05.png":{frame:{x:26,y:141,w:20,h:33},rotated:!1,trimmed:!1,spriteSourceSize:{x:0,y:0,w:20,h:33},sourceSize:{w:20,h:33},pivot:{x:.5,y:.5}},"02_06.png":{frame:{x:141,y:100,w:20,h:31},rotated:!1,trimmed:!1,spriteSourceSize:{x:0,y:0,w:20,h:31},
sourceSize:{w:20,h:31},pivot:{x:.5,y:.5}},"02_07.png":{frame:{x:1,y:176,w:22,h:33},rotated:!1,trimmed:!1,spriteSourceSize:{x:0,y:0,w:22,h:33},sourceSize:{w:22,h:33},pivot:{x:.5,y:.5}},"02_08.png":{frame:{x:1,y:211,w:22,h:33},rotated:!1,trimmed:!1,spriteSourceSize:{x:0,y:0,w:22,h:33},sourceSize:{w:22,h:33},pivot:{x:.5,y:.5}},"02_09.png":{frame:{x:57,y:210,w:23,h:32},rotated:!1,trimmed:!1,spriteSourceSize:{x:0,y:0,w:23,h:32},sourceSize:{w:23,h:32},pivot:{x:.5,y:.5}},"02_10.png":{frame:{x:124,y:34,w:23,
h:31},rotated:!1,trimmed:!1,spriteSourceSize:{x:0,y:0,w:23,h:31},sourceSize:{w:23,h:31},pivot:{x:.5,y:.5}},"02_11.png":{frame:{x:1,y:106,w:24,h:33},rotated:!1,trimmed:!1,spriteSourceSize:{x:0,y:0,w:24,h:33},sourceSize:{w:24,h:33},pivot:{x:.5,y:.5}},"02_12.png":{frame:{x:97,y:34,w:25,h:31},rotated:!1,trimmed:!1,spriteSourceSize:{x:0,y:0,w:25,h:31},sourceSize:{w:25,h:31},pivot:{x:.5,y:.5}},"03_01.png":{frame:{x:196,y:34,w:19,h:31},rotated:!1,trimmed:!1,spriteSourceSize:{x:0,y:0,w:19,h:31},sourceSize:{w:19,
h:31},pivot:{x:.5,y:.5}},"03_02.png":{frame:{x:160,y:67,w:20,h:31},rotated:!1,trimmed:!1,spriteSourceSize:{x:0,y:0,w:20,h:31},sourceSize:{w:20,h:31},pivot:{x:.5,y:.5}},"03_03.png":{frame:{x:174,y:34,w:20,h:31},rotated:!1,trimmed:!1,spriteSourceSize:{x:0,y:0,w:20,h:31},sourceSize:{w:20,h:31},pivot:{x:.5,y:.5}},"03_04.png":{frame:{x:176,y:1,w:20,h:31},rotated:!1,trimmed:!1,spriteSourceSize:{x:0,y:0,w:20,h:31},sourceSize:{w:20,h:31},pivot:{x:.5,y:.5}},"03_05.png":{frame:{x:152,y:133,w:20,h:31},rotated:!1,
trimmed:!1,spriteSourceSize:{x:0,y:0,w:20,h:31},sourceSize:{w:20,h:31},pivot:{x:.5,y:.5}},"03_06.png":{frame:{x:163,y:100,w:20,h:31},rotated:!1,trimmed:!1,spriteSourceSize:{x:0,y:0,w:20,h:31},sourceSize:{w:20,h:31},pivot:{x:.5,y:.5}},"03_07.png":{frame:{x:107,y:201,w:22,h:31},rotated:!1,trimmed:!1,spriteSourceSize:{x:0,y:0,w:22,h:31},sourceSize:{w:22,h:31},pivot:{x:.5,y:.5}},"03_08.png":{frame:{x:129,y:166,w:22,h:31},rotated:!1,trimmed:!1,spriteSourceSize:{x:0,y:0,w:22,h:31},sourceSize:{w:22,h:31},
pivot:{x:.5,y:.5}},"03_09.png":{frame:{x:126,y:1,w:23,h:31},rotated:!1,trimmed:!1,spriteSourceSize:{x:0,y:0,w:23,h:31},sourceSize:{w:23,h:31},pivot:{x:.5,y:.5}},"03_10.png":{frame:{x:99,y:1,w:25,h:31},rotated:!1,trimmed:!1,spriteSourceSize:{x:0,y:0,w:25,h:31},sourceSize:{w:25,h:31},pivot:{x:.5,y:.5}},"03_11.png":{frame:{x:90,y:100,w:24,h:31},rotated:!1,trimmed:!1,spriteSourceSize:{x:0,y:0,w:24,h:31},sourceSize:{w:24,h:31},pivot:{x:.5,y:.5}},"03_12.png":{frame:{x:82,y:204,w:23,h:31},rotated:!1,trimmed:!1,
spriteSourceSize:{x:0,y:0,w:23,h:31},sourceSize:{w:23,h:31},pivot:{x:.5,y:.5}},"04_01.png":{frame:{x:104,y:168,w:23,h:31},rotated:!1,trimmed:!1,spriteSourceSize:{x:0,y:0,w:23,h:31},sourceSize:{w:23,h:31},pivot:{x:.5,y:.5}},"04_02.png":{frame:{x:105,y:133,w:23,h:31},rotated:!1,trimmed:!1,spriteSourceSize:{x:0,y:0,w:23,h:31},sourceSize:{w:23,h:31},pivot:{x:.5,y:.5}},"04_03.png":{frame:{x:116,y:100,w:23,h:31},rotated:!1,trimmed:!1,spriteSourceSize:{x:0,y:0,w:23,h:31},sourceSize:{w:23,h:31},pivot:{x:.5,
y:.5}},"04_04.png":{frame:{x:135,y:67,w:23,h:31},rotated:!1,trimmed:!1,spriteSourceSize:{x:0,y:0,w:23,h:31},sourceSize:{w:23,h:31},pivot:{x:.5,y:.5}},"04_05.png":{frame:{x:149,y:34,w:23,h:31},rotated:!1,trimmed:!1,spriteSourceSize:{x:0,y:0,w:23,h:31},sourceSize:{w:23,h:31},pivot:{x:.5,y:.5}},"04_06.png":{frame:{x:151,y:1,w:23,h:31},rotated:!1,trimmed:!1,spriteSourceSize:{x:0,y:0,w:23,h:31},sourceSize:{w:23,h:31},pivot:{x:.5,y:.5}},"04_07.png":{frame:{x:67,y:1,w:30,h:31},rotated:!1,trimmed:!1,spriteSourceSize:{x:0,
y:0,w:30,h:31},sourceSize:{w:30,h:31},pivot:{x:.5,y:.5}},"04_08.png":{frame:{x:60,y:102,w:28,h:31},rotated:!1,trimmed:!1,spriteSourceSize:{x:0,y:0,w:28,h:31},sourceSize:{w:28,h:31},pivot:{x:.5,y:.5}},"04_09.png":{frame:{x:48,y:138,w:29,h:31},rotated:!1,trimmed:!1,spriteSourceSize:{x:0,y:0,w:29,h:31},sourceSize:{w:29,h:31},pivot:{x:.5,y:.5}},"04_10.png":{frame:{x:49,y:69,w:31,h:31},rotated:!1,trimmed:!1,spriteSourceSize:{x:0,y:0,w:31,h:31},sourceSize:{w:31,h:31},pivot:{x:.5,y:.5}},"04_11.png":{frame:{x:47,
y:176,w:29,h:32},rotated:!1,trimmed:!1,spriteSourceSize:{x:0,y:0,w:29,h:32},sourceSize:{w:29,h:32},pivot:{x:.5,y:.5}},"04_12.png":{frame:{x:64,y:34,w:31,h:31},rotated:!1,trimmed:!1,spriteSourceSize:{x:0,y:0,w:31,h:31},sourceSize:{w:31,h:31},pivot:{x:.5,y:.5}}},meta:{app:"http://www.codeandweb.com/texturepacker",version:"1.0",image:"zombie.png",format:"RGBA8888",size:{w:256,h:256},scale:"1",smartupdate:"$TexturePacker:SmartUpdate:b1a8239df44e5fd06d095f7e7c0f3e84:de4104427ba80a233fc29931863a18a5:671cfcca2facf02865d2d7530477df67$"}};
sceneJSON={frames:{"grass_01.png":{frame:{x:115,y:90,w:27,h:21},rotated:!1,trimmed:!0,spriteSourceSize:{x:3,y:6,w:27,h:21},sourceSize:{w:31,h:31},pivot:{x:.5,y:.5}},"grass_02.png":{frame:{x:115,y:35,w:31,h:30},rotated:!1,trimmed:!0,spriteSourceSize:{x:0,y:1,w:31,h:30},sourceSize:{w:31,h:31},pivot:{x:.5,y:.5}},"grass_03.png":{frame:{x:115,y:67,w:30,h:21},rotated:!1,trimmed:!0,spriteSourceSize:{x:1,y:6,w:30,h:21},sourceSize:{w:31,h:31},pivot:{x:.5,y:.5}},"grass_04.png":{frame:{x:205,y:80,w:44,h:43},
rotated:!1,trimmed:!0,spriteSourceSize:{x:1,y:2,w:44,h:43},sourceSize:{w:45,h:45},pivot:{x:.5,y:.5}},"grass_05.png":{frame:{x:155,y:1,w:50,h:44},rotated:!1,trimmed:!0,spriteSourceSize:{x:0,y:3,w:50,h:44},sourceSize:{w:50,h:50},pivot:{x:.5,y:.5}},"grass_06.png":{frame:{x:79,y:175,w:48,h:45},rotated:!1,trimmed:!0,spriteSourceSize:{x:2,y:4,w:48,h:45},sourceSize:{w:50,h:50},pivot:{x:.5,y:.5}},"grass_07.png":{frame:{x:205,y:48,w:45,h:30},rotated:!1,trimmed:!0,spriteSourceSize:{x:4,y:10,w:45,h:30},sourceSize:{w:50,
h:50},pivot:{x:.5,y:.5}},"grass_08.png":{frame:{x:115,y:1,w:36,h:32},rotated:!1,trimmed:!0,spriteSourceSize:{x:7,y:9,w:36,h:32},sourceSize:{w:50,h:50},pivot:{x:.5,y:.5}},"grass_09.png":{frame:{x:155,y:47,w:48,h:44},rotated:!1,trimmed:!0,spriteSourceSize:{x:1,y:4,w:48,h:44},sourceSize:{w:50,h:50},pivot:{x:.5,y:.5}},"grass_10.png":{frame:{x:207,y:1,w:48,h:45},rotated:!1,trimmed:!0,spriteSourceSize:{x:1,y:5,w:48,h:45},sourceSize:{w:50,h:50},pivot:{x:.5,y:.5}},"grass_11.png":{frame:{x:113,y:222,w:40,
h:32},rotated:!1,trimmed:!0,spriteSourceSize:{x:5,y:12,w:40,h:32},sourceSize:{w:50,h:50},pivot:{x:.5,y:.5}},"grass_12.png":{frame:{x:36,y:67,w:31,h:26},rotated:!1,trimmed:!0,spriteSourceSize:{x:9,y:13,w:31,h:26},sourceSize:{w:50,h:50},pivot:{x:.5,y:.5}},"grass_13.png":{frame:{x:54,y:175,w:23,h:66},rotated:!1,trimmed:!0,spriteSourceSize:{x:8,y:2,w:23,h:66},sourceSize:{w:39,h:70},pivot:{x:.5,y:.5}},"grass_14.png":{frame:{x:34,y:175,w:18,h:18},rotated:!1,trimmed:!0,spriteSourceSize:{x:1,y:2,w:18,h:18},
sourceSize:{w:20,h:20},pivot:{x:.5,y:.5}},"grass_15.png":{frame:{x:144,y:90,w:9,h:15},rotated:!1,trimmed:!0,spriteSourceSize:{x:1,y:0,w:9,h:15},sourceSize:{w:10,h:15},pivot:{x:.5,y:.5}},"ground_01.png":{frame:{x:34,y:99,w:79,h:74},rotated:!1,trimmed:!1,spriteSourceSize:{x:0,y:0,w:79,h:74},sourceSize:{w:79,h:74},pivot:{x:.5,y:.5}},"ground_02.png":{frame:{x:1,y:197,w:50,h:52},rotated:!1,trimmed:!1,spriteSourceSize:{x:0,y:0,w:50,h:52},sourceSize:{w:50,h:52},pivot:{x:.5,y:.5}},"tower_01.png":{frame:{x:1,
y:1,w:33,h:96},rotated:!1,trimmed:!1,spriteSourceSize:{x:0,y:0,w:33,h:96},sourceSize:{w:33,h:96},pivot:{x:.5,y:.5}},"tower_02.png":{frame:{x:1,y:99,w:31,h:96},rotated:!1,trimmed:!1,spriteSourceSize:{x:0,y:0,w:31,h:96},sourceSize:{w:31,h:96},pivot:{x:.5,y:.5}},"tower_03.png":{frame:{x:79,y:222,w:32,h:33},rotated:!1,trimmed:!0,spriteSourceSize:{x:0,y:63,w:32,h:33},sourceSize:{w:32,h:96},pivot:{x:.5,y:.5}}},meta:{app:"http://www.codeandweb.com/texturepacker",version:"1.0",image:"scene.png",format:"RGBA8888",
size:{w:256,h:256},scale:"1",smartupdate:"$TexturePacker:SmartUpdate:42a07bebeec4a6063545b2f12f816a57:981322ee434e4365c29a90d5f2bc91e4:b5ae526252a9bb5f811c6329b74d8d84$"}};
turretJSON={frames:{"turret_01_1.png":{frame:{x:103,y:1,w:128,h:86},rotated:!1,trimmed:!0,spriteSourceSize:{x:0,y:7,w:128,h:86},sourceSize:{w:128,h:100},pivot:{x:.5,y:.5}},"turret_01_2.png":{frame:{x:1,y:95,w:128,h:88},rotated:!1,trimmed:!0,spriteSourceSize:{x:0,y:5,w:128,h:88},sourceSize:{w:128,h:100},pivot:{x:.5,y:.5}},"turret_01_3.png":{frame:{x:131,y:89,w:128,h:86},rotated:!1,trimmed:!0,spriteSourceSize:{x:0,y:7,w:128,h:86},sourceSize:{w:128,h:100},pivot:{x:.5,y:.5}},"turret_02.png":{frame:{x:1,
y:185,w:69,h:56},rotated:!1,trimmed:!0,spriteSourceSize:{x:3,y:4,w:69,h:56},sourceSize:{w:76,h:65},pivot:{x:.5,y:.5}},"turret_03.png":{frame:{x:131,y:177,w:96,h:76},rotated:!1,trimmed:!0,spriteSourceSize:{x:3,y:12,w:96,h:76},sourceSize:{w:103,h:100},pivot:{x:.5,y:.5}},"turret_04.png":{frame:{x:1,y:1,w:100,h:92},rotated:!1,trimmed:!1,spriteSourceSize:{x:0,y:0,w:100,h:92},sourceSize:{w:100,h:92},pivot:{x:.5,y:.5}},"turret_06.png":{frame:{x:72,y:185,w:47,h:52},rotated:!1,trimmed:!0,spriteSourceSize:{x:1,
y:0,w:47,h:52},sourceSize:{w:50,h:52},pivot:{x:.5,y:.5}}},meta:{app:"http://www.codeandweb.com/texturepacker",version:"1.0",image:"turret.png",format:"RGBA8888",size:{w:260,h:254},scale:"1",smartupdate:"$TexturePacker:SmartUpdate:2514075745d851438dfc3478c612e327:47edb90f578132f7b9be299225601cdc:26057a831b32959680a28025ef05a3b1$"}};
